confluentinc/kafka-connect-jdbc

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/JdbcUtils.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/JdbcUtilsTest.java

Because this is checked before making any queries, this is only checked for
table-based copying. Custom queries would either require specifying a
table.column format for the check, which wouldn't guarantee it even matched up
with the query, or require parsing or executing the query to perform the
validation before normal polling could start.

Add check for NOT NULL columns on target tables when specified as increasing or timestamp column for offsets.

---

docs/index.rst

Add schema evolution in doc

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/TimestampIncrementingOffset.java
src/main/java/io/confluent/connect/jdbc/TimestampIncrementingTableQuerier.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/TimestampIncrementingOffsetTest.java

Originally, I ran into an issue where PostgreSQL timestamps have microsecond precision, but the offsets were stored with millisecond precision. Consequently, several records would _always_ be extracted on every poll because the extra microseconds of precision caused those records to _always_ be "newer" than the stored offset.
The logic to save and restore nanosecond precision on a `java.sql.Timestamp` was non-trivial, so I thought it would be good to abstract the offsets into its own class `TimestampIncrementingOffset`. Wrote some tests for it too.
Open to comments and suggestions.
Thanks!

CC-69: support nanoseconds precision for timestamp-based offset tracking

---

src/main/java/io/confluent/connect/jdbc/TimestampIncrementingOffset.java

if JSON converter is in use we can get a Long back even if an Integer is used at storage time

CC-243: use Long for nanos in offset map rather than Integer

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/test/java/io/confluent/connect/jdbc/sink/SinkTaskTest.java

If custom configuration is desired for some topics, tables etc. currently going to go with expecting users to start multiple connectors

Remove 'contextual' config bits

---

src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java

Currently the sink doesn't support the logical types:
* `org.apache.kafka.connect.data.Date`
* `org.apache.kafka.connect.data.Time`
* `org.apache.kafka.connect.data.Timestamp`
* `org.apache.kafka.connect.data.Decimal`
The fields with such types have primitive schema type, but also a name.
The logical type is determined by the name.
When the converter see a logical type it converts the value to some higher level type:
* `Date`: from `int` to `java.util.Date`
* `Time`: from `int` to `java.util.Date`
* `Timestamp`: from `long` to `java.util.Date`
* `Decimal`: from `bytes[]` to `BigDecimal`
The problem is that the statement builder doesn't know that. For example it thinks that `Timestamp` is `long`, but it is `java.util.Date`.
I don't write much Java and maybe the code is not very good, but …

CC-278: Sink: support Connect schema logical types

---

src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

Few of the tables in our legacy MySQL schema have a tinyint value as ID columns. These are also auto-incrementing and hence would be the incrementing.id.column values in the properties file. But when we try to run this with that setting, following exception is thrown:
org.apache.kafka.connect.errors.ConnectException: Invalid type for incrementing column: INT8
at io.confluent.connect.jdbc.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:191)
at io.confluent.connect.jdbc.JdbcSourceTask.poll(JdbcSourceTask.java:217)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
at …

supporting tinyint for primary key

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/BulkTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java
src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/sink/SqliteHelperTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcUtilsTest.java
src/test/java/io/confluent/connect/jdbc/source/TableMonitorThreadTest.java

This adds the ability to configure jdbc schemaPattern from connector configuration.
Reported here https://github.com/confluentinc/kafka-connect-jdbc/issues/32

Ability to set the schema pattern for tables metadata retrieval

---

src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerierTest.java

Only supported when the scale is 0 (i.e. it is an integer) and <= Long.MAX_VALUE, so we can continue storing it as a long for implementation simplicity
Fixes #31 and #125

CC-311: support for Decimal logical type as incrementing column

---

src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/DbDialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/GenericDialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/HANADialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/MySqlDialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/OracleDialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/PostgreSqlDialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/SqlServerDialect.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/SqliteDialect.java
src/main/java/io/confluent/connect/jdbc/sink/metadata/FieldsMetadata.java
src/main/java/io/confluent/connect/jdbc/sink/metadata/SinkRecordField.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/HANADialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/MySqlDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/OracleDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/PostgreSqlDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/SqlServerDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/SqliteDialectTest.java

Converts Kafka Connect logical types into their database-specific datatypes rather than using the underlying internal datatypes. Currently, only the PostgresSqlDialect is supported. 
This handles issue https://github.com/confluentinc/kafka-connect-jdbc/issues/133.

Provide better support for logical types in sink

---

src/main/java/io/confluent/connect/jdbc/sink/dialect/DbDialect.java

SimpleDateFormat is not thread-safe and this flow runs inside the sink tasks which run concurrently with each other, so this may incur in concurrency issues. 3 options for this would be 1) create a separate instance each time, 2) synchronise the access to the formatter 3) declare it as thread local.
I'm suggesting option 3) in this PR, as from past experience it's the one from the above with less performance impacts.
There are 2 more options, both are thread-safe but require an extra dependency to be added: 4) joda-time DateTimeFormatter, 5) commons-lang FastDateFormat.
Any feedback is welcome.

Declaring SimpleDateFormat as thread-local

---

src/main/java/io/confluent/connect/jdbc/sink/dialect/MySqlDialect.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/MySqlDialectTest.java

DATETIME supports a wider range by default, see http://dev.mysql.com/doc/refman/5.5/en/datetime.html

Change default MySQL Schema.Type.TIMESTAMP mapping from TIMESTAMP to DATETIME

---

src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/DbDialect.java
src/main/java/io/confluent/connect/jdbc/source/DataConverter.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/source/MockTime.java

Use UTC Calendar when binding date/times in sink; fix thread-unsafe usage of UTC_CALENDAR in TimestampIncrementingTableQuerier

---

src/main/java/io/confluent/connect/jdbc/source/DataConverter.java

Note Derby DB doesn't support unsigned numeric types so unfortunately unable to add test cases for them.

Fixes issue #165. Widen schema types for unsigned numeric types.

---

pom.xml

The current process for building rpm's is kind of a pain. Especially for something small like back porting a fix. Also RPM based hot fixes are a preferred distribution method over one off jars for quick fixes.  
There is also a deb plugin which can be utilized for the same.

add rpm build to lifecycle 

---

src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java

Fix for the issue discribed in https://groups.google.com/forum/#!topic/confluent-platform/nP34b-P2JVA.
JDBC allows returning a value of -2 (Statement.SUCCESS_NO_INFO) when executing a batch insert/update, which means that operation was successful but number of rows returned is unknown.

Statement.SUCCESS_NO_INFO should be treated in BufferedRecords.flush

---

src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/DbDialect.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/MySqlDialectTest.java

I needed a way to just update existing records from tables, and I added this UPDATE mode for JDBC Sink Connector. This creates UPDATE queries based on the primary keys.
I think this could be useful for other as well.
Thank you,
Maria

JDBC Sink Connector - Add insert.mode = UPDATE, that generates only update queries

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java

Used try-with-resources to ensure the JDBC connection is always closed.
This fix is based on the `3.3.x` branch so that it will be included in the next 3.3.x release.

CC-1064 Corrected the table name recommender to always close the JDBC connection

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcUtilsTest.java

The JDBC source connector’s recommender for table names can take a long time when the database has a large number of tables. And, the recommender is used for both the table whitelist and blacklist properties.
This PR makes a number of improvements. First, the recommender now uses the table types to reduce the number of results that must be processed when determining the names of the available tables. This may help to reduce the number of tables returned by the recommender if a different set of tables is required. For example, if only views are to be used, then the table types property can be set to `VIEW` and the recommender will correctly return only the available views.
Secondly and more importantly, the table name recommender used for both the whitelist and blacklist properties will …

CC-1065 Source connector’s recommender uses table type filter and caches results

---

src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskTestBase.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java

A [recent change to the Kafka dependencies](https://github.com/apache/kafka/pull/3881) included an upgrade of the PowerMock library to 2.0.0-beta5 for JDK9 reasons, but this appears to have broken several tests in this JDBC connector repository.
Apparently, with the new 2.0.0-beta5 version it is better to use `@Mock` annotations on member fields rather than to manually create the (local or member field) mock instances via `PowerMock.createMock(MyClass.class)`. Unfortunately this requires running the concrete test classes via `@RunWith(PowerMockRunner.class)` and several other class-level annotations, which is more verbose.

CC-1266: Corrected build by changing PowerMock uses

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java

The original forked repo for #291 was deleted by accident so I cannot commit to that PR anymore. This PR is the final fix.
======== Original PR Note ========
Currently when there's error from db side, the error log shows as follow:
```
java.sql.BatchUpdateException: Batch entry 0 `INSERT INTO ....` was aborted.  Call getNextException to see the cause.
```
Instead, it should show the actual error that retrieved from `getNextException`.
This PR add that error message to log.

Log out actual sql exceptions (fix for #291)

---

docs/includes/prerequisites.rst
docs/sink_connector.rst
docs/source_connector.rst

Staging server:
- http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/PR/663/3.3.0/connect/connect-jdbc/docs/source_connector.html#quick-start
- http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/PR/663/3.3.0/connect/connect-jdbc/docs/sink_connector.html#quick-start

DOCS-171 - add prerequisites for JDBC Source Connector quickstart

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java

I went through the code to find possible places where a ResultSet might not be closed.  The only case seems to be in poll(), when either an exception occurs or the task is shutdown.    According to https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection, ResultSets should be closed even if the Connection is subsequently closed.  Again, this seems to be the only place where a ResultSet could go unclosed.

CC-1366: close ResultSets and Statements during shutdown

---

src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java
src/main/java/io/confluent/connect/jdbc/sink/metadata/TableMetadataLoadingCache.java
src/test/java/io/confluent/connect/jdbc/sink/DbStructureTest.java

Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-1878: Allow for case differences while finding missing columns

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/MySqlDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java

Setting the fetch direction does not work with some versions of SQLite and potentially other DBMSes. Since the 4.1.1 source connector did not use this method, the generic dialect should not set the fetch direction and instead only the PostgreSQL and MySQL dialects should do this since those drivers respect and use this to reduce memory problems.
The most straightforward way to handle this is to create a new protected method in `GenericDatabaseDialect` that is to perform any operations on a newly-created prepared statement, and by default to do nothing. Then the `PostgreSqlDatabaseDialect` and `MySqlDatabaseDialect` can override this and call the `setFetchDirection` method.

CC-2139: Moved the call to set the fetch direction out of generic dialect

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConstants.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/OffsetProtocols.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskTestBase.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java

With the dialect changes introduced in 5.0.x, the JDBCSourceTask always gets the table names as fully qualified table names. In the offset management, the connector was using the unqualified table name while writing the offsets and fully qualified table name for reading the offsets. Because of this when a connector restarts, it never finds the stored offsets and hence always starts from the beginning. This issue occurs only for TABLE mode.
The solution is to include a backward compatible offset management. We do the following
- Introduce a new offset protocol version. This will help evolve any changes to offsets in future.
- Offset writes will always follow new protocol version which is to include the FQN of the table
- During read, we include both the new protocol version offset key and …

CC-2116: Fix offsets compatibility

---

src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java

The first call to closeQuietly is guaranteed by the stop method. But the
second one will only happen if control reaches the updateTables() method
in TableMonitorThread. This can be skipped in cases where
TableMonitorThread's run() method detects a shutdown scenario to simply
exit and not poll the source table.
Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-2436: Test for method call to occur at least once

---

docs/includes/prerequisites.rst
docs/index.rst
docs/sink-connector/index.rst
docs/sink-connector/sink_config_options.rst
docs/source-connector/index.rst
docs/source-connector/source_config_options.rst

- simplifies doc design by moving the child sink_connector.rst and source_connector.rst  pages contents to their own subfolders.
- moved config_options. rst files to the respective subfolders
- added include which points to shared connector install include for reuse across all connectors.
- adds text string replace for common terms (e.g. Kafka Connect)
- changes titles to match naming shown at https://www.confluent.io/hub/#
- redirect added here https://github.com/confluentinc/docs/pull/1146/

DOCS-618 - Refactor Connect docs

---

pom.xml

Bump up version of the sqlite-jdbc library used for testing as embedded database in order to benefit of making use of jdbc4 classes.

MINOR: bump up version of sqlite-jdbc library to the latest version available

---

pom.xml
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/main/java/io/confluent/connect/jdbc/util/TimeZoneValidator.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java
src/test/java/io/confluent/connect/jdbc/util/TimeZoneValidatorTest.java

Added db.timezone setting in order to be able to customize the timezone (to a different value than the default value UTC) used at the jdbc level.
When customizing this setting, the  date/time/timestamp values read from the source database will be instantiated with the customized time zone.
The timestamp  1474661402123L  corresponds to `2016-09-23 20:10:02.123` in UTC zone.
When the database timezone is not UTC, but Europe/Vienna, the value  read from the database should be `2016-09-23 22:10:02.123`.
This pull requests addresses exactly the problem mentioned in the example above, by allowing the user of kafka-jdbc connector to customize the timezone in which the date/time/timestamp values are read from the database.
This is being done by adding a new `timezone` field to …

Added db.timezone setting 

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java

The JDBC source task was attempting to close the CachedConnectionProvider and its connections when the task was stopped, which happens asynchronously while the `poll()` method may be still working in the task’s primary thread. If the connection provider is closed but is needed again, it will reopen connections as needed but these will never be closed.
With this change, the connection provider is closed at the end of `poll()` after the task has been stopped (or after an exception has been thrown) and after the connections are no longer being used.

CC-2910: Changed source task to close connections when finished

---

src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java
src/main/java/io/confluent/connect/jdbc/sink/metadata/SchemaPair.java

This will illuminate why we flush, either because of mismatched
schemas, batch size limits, or processed entire message batch.

MINOR Add log statements to debug different flush paths

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java

The sink connector uses this type when it creates the table in the database.
1. Backward compatibility - `BLOB` doesn't exist in PostgreSQL, so the previous code never worked. Also, because only the `PostgresqlDialect` is changed, this change does not affect other DBMSes (unless they use the PostgreSQL dialect).
2. The dialect also uses `statement.setBytes(index, bytes)` ([see code](https://github.com/confluentinc/kafka-connect-jdbc/blob/309d4454b410573d0de37ff3219e888cb6aae554/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1462)) to set the column values, and the PostgreSQL JDBC driver will correctly binary set values for `BYTEA` columns. Basically, `BYTEA` is pretty much PostgreSQL's `BLOB` type.
Fixes #404, #324 
Supersedes #271 which is not currently …

CC-3414: Changed PostgreSQL dialect to use BYTEA rather than BLOB

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

The INFO-level log message about creating query was introduced recently, but INFO level results in the message being logged too frequently (about every 5 seconds). It has been reduced to DEBUG-level.

CC-3525: Reduced log message for creating query

---

src/main/java/io/confluent/connect/jdbc/source/BulkTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

This will log at INFO level the parameterized query statements the first time their used (or if they change), so that users don't have to change to DEBUG level to know what these query statements are. The existing DEBUG statements will continue to be logged *every* time the queries are generated and executed.
Fixes #559

CC-3578: Logging query for source connector at INFO level only the first time it's used

---

src/test/java/io/confluent/connect/jdbc/dialect/SqliteDatabaseDialectTest.java

DateTimeUtils in branch 5.2.x has function ```getTimeZoneCalendar()``` instead of ```UTC_CALENDAR.get()```
Modifying unit test ```useCurrentTimestampValue()``` in ```SqliteDatabaseDialect.java``` to use the updated function

MINOR: CC-3812: Update unit test to use updated DateTimeUtils function

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/main/java/io/confluent/connect/jdbc/util/TimeZoneValidator.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqliteDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java
src/test/java/io/confluent/connect/jdbc/util/TimeZoneValidatorTest.java

Date/time/timestamp values read from the source DB will be
instantiated into the specified timezone
Original PR: https://github.com/confluentinc/kafka-connect-jdbc/pull/505/commits
https://confluentinc.atlassian.net/browse/ESCALATION-910
Follow-on task will be to further backport to 4.1.x

Backport db.timzeone config

---

src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/main/java/io/confluent/connect/jdbc/sink/dialect/DbDialect.java
src/main/java/io/confluent/connect/jdbc/source/BulkTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/DataConverter.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/main/java/io/confluent/connect/jdbc/util/TimeZoneValidator.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/sink/dialect/DbDialectTest.java
src/test/java/io/confluent/connect/jdbc/source/DataConverterTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerierTest.java
src/test/java/io/confluent/connect/jdbc/util/TimeZoneValidatorTest.java

Date/time/timestamp values read from the source DB will be
instantiated into the specified timezone.
Backports https://github.com/confluentinc/kafka-connect-jdbc/pull/505/files
4.1.x must support Java 7, explaining some of the deviations from the original.
The strategy is to minimize changing public interfaces of the 4.1.x branch, even if it requires deviation from the 5.x feature and changes to the tests files in 4.1.x. Notably, I decided that `DbDialect.withTimeZone(TimeZone)` is the best way to provide timezones to the Column Formatters, even though it opens the potential for NPE if the DbDialect object is never given a timezone, since it is impossible for the user to misconfigure it is an acceptable tradeoff.

Backport db.timzeone config to 4.1.x

---

src/main/java/io/confluent/connect/jdbc/util/TimeZoneValidator.java
src/test/java/io/confluent/connect/jdbc/util/TimeZoneValidatorTest.java

Fixes build error since 4.1.x should support Java 7.
The behavior is slightly more limited than in the 5.x version, as demonstrated in the tests. The docs will reflect that in the 4.1.x version the valid timezones are listed by `TimeZone.getAvailableIDs()`

Use Java 7 to valiate timezones

---

src/main/java/io/confluent/connect/jdbc/dialect/Db2DatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/Db2DatabaseDialectTest.java

This fix was included in 4.1.x
https://github.com/confluentinc/kafka-connect-jdbc/blob/4.1.x/src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java#L249
but lost when the code was refactored from 5.0.x to 5.1.x
One big shortcoming here is that there seems to be no testing against this, but the only way to really know would be to have an integration test that spins up a DB2 instance. Any other tests against this are kind of over-specific, and what we really want to know is that this works against DB2. Sadly this is pressing issue for users so no time to write integration test.

CC-4423 Remove semicolon from Db2 dialect timestamp query

---

src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/main/java/io/confluent/connect/jdbc/util/DeleteEnabledRecommender.java
src/main/java/io/confluent/connect/jdbc/util/PrimaryKeyModeRecommender.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcDbWriterTest.java

A record with `null` value is considered a tombstone event and result in deleting the corresponding row in the destination table.
Deletes are disabled by default. Set config `delete.enabled` to `true` to enable. Also requires `pk.mode = record_key` otherwise it can't find the record to delete.
Tested against Postgres
Fixes #607 and fixes #127

Fixes #127. Added delete support for sink.

---

src/main/java/io/confluent/connect/jdbc/JdbcSinkConnector.java

This will allow variants of the JdbcSinkConnector to extend the class
rather than being forced to delegate the functionality, or copy the code.
This is desirable for promoting code-reuse in new connectors under development.

MINOR: Remove the final keyword from JdbcSinkConnector

---

src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java

When sinking data to SqlServer with table auto-creation is enabled and primary key is string type, it was using varchar(max) for primary key, which leads to the exception:
```
com.microsoft.sqlserver.jdbc.SQLServerException: Column in table is of a type that is invalid for use as a key column in an index
```
https://github.com/confluentinc/kafka-connect-jdbc/issues/379
SqlServer 2012(and before) allows `varchar(900)` to be primary key. More than that is not acceptable.
As other RDBMS related sinks identify string type primary key and set it particularly, it makes sens to adapt it for MSSQL sink.

SqlServerDialect uses varchar(900) for primary key as string type

---

src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java

As-is, the SLF4J logger created and used by the `TableQuerier` class produces confusing log messages that end in, for example, `BulkTableQuerier:140`, which is counterintuitive since the `BulkTableQuerier` file has fewer than 140 lines.
This change alters that logger to refer to the `TableQuerier` class instead.

Change TableQuerier log to use real class name for file

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java

1) make log messages clearer after filtering tables
2) when no readable tables are available, don't run tasks and inform user via log

CC-4946: changing log msgs on filtering and avoiding frequently retrying tasks when no tables

---

pom.xml

Aims to fix https://github.com/confluentinc/kafka-connect-jdbc/issues/494
Version is only upgraded to a bugfix so it can be backported to 5.0.x and more recent

MINOR: Upgrade postgress jdbc driver to most recent bugfix release (9.4.1212)

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java

I've bumped into the problem:
```
[2019-07-08 20:05:06,314] ERROR Graceful stop of task deals-0 failed. (org.apache.kafka.connect.runtime.Worker)
```
Which leads to duplicates in kafka topics while rebalancing.
The reason is that JDBC source task is sleeping in `poll()` too much (exactly `POLL_INTERVAL_MS_CONFIG` which is 60000 ms in my case). And worker is unable to finish all tasks in `task.shutdown.graceful.timeout.ms` which is 5000 ms by default.
This can be seen in the log below (see `***` marks):
```
[2019-07-08 20:04:59,929] DEBUG WorkerSourceTask{id=deals-0} About to send 100 records to Kafka (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-07-08 20:04:59,935] TRACE {} Polling for new data (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2019-07-08 20:04:59,935] DEBUG …
```

Fix `ERROR Graceful stop of task failed`

---

README.md

This fix will warn customers to consider integration tests before contributing a dialect.

Update readme to indicate integration tests are required

---

Jenkinsfile

Currently developers are running pint merge manually for the commits to
merge back the commits to the master and then jenkins is verifying if
the pint merge is already done or not.
Recently dev tools team made a change to run pint merge within Jenkins
ci without any effort from developers until there is a conflict. This
commit is to onboard this repo with the pint ci auto merge.
- Verified the PR job has the  pintMerge option enabled.

Onboarding with for the pint auto merge in Jenkins

---

src/main/java/io/confluent/connect/jdbc/util/TableDefinitions.java

This prevents shadowing table create permission exceptions

MINOR: Avoid NPE when columns cannot be described

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java

The CachedConnectionProvider was being mocked with PowerMock's `expectNew` function, which requires rewriting the binary classes that contain call sites for CachedConnectionProvider::new. It would be simpler to just isolate the construction of this dependency to a protected method than to use this high-power mocking functionality.

CC-6747: Replace static mocking for the CachedConnectionProvider

---

src/main/java/io/confluent/connect/jdbc/sink/metadata/SinkRecordField.java

This will allow for database dialects to make deeper inspections of SinkRecord fields (`ARRAY`, `STRUCT`, and `MAP` types), when previously only the broad type of the schema was known.

MINOR: Expose SinkRecordField schema to database dialects

---

src/main/java/io/confluent/connect/jdbc/source/DataConverter.java

Added support for SQL Server’s DateTimeOffset type, relying upon the MS SQL Server JDBC driver that does support the DateTimeOffset type.
Fixes #614 for `4.0.x` and `4.1.x`. See #750 for the fix for `5.0.x` and later.

CC-7265: Add support for SQL Server DateTimeOffset type

---

src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialects.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java

Added support for SQL Server’s DateTimeOffset type. 
This change supports the jTDS driver that we ship by default, and even the latest version of this driver (which is pretty old) doesn't have support for DateTimeOffset. Per [MS documentation](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15), the dialect handles DateTimeOffset values by getting the string form of the DateTimeOffset and parsing them into a Timestamp.
The MS SQL Server JDBC driver does support the DateTimeOffset type, so when this driver is used the dialect simply delegates to the driver to get the timestamp for the column.
Fixes #614 for `5.0.x` and later. See #752 for a fix for the `4.0.x` and `4.1.x` branches.

CC-7265: Support SQL Server DateTimeOffset

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/Db2DatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/DerbyDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/MySqlDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SapHanaDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqliteDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/VerticaDatabaseDialectTest.java

Addressing ticket CC-7382: https://confluentinc.atlassian.net/browse/CC-7382, which comes from triaging this issue https://github.com/confluentinc/kafka-connect-jdbc/issues/755. 
The issue is reporting a bug of postgres dialect of jdbc connector. When there is boolean column with default value, there will be an exception. The bug is caused by us using 0/1 as default values for boolean type, which is not recognized by postgres. 
My fix is to overwrite `formatColumnValue()` to do special handling on boolean default for postgres. And I extended the unit test to test the changes. 
My code passed unit tests, and I have manually tested on postgres instance. It works as intended.

CC-7382: use true/false as default values for boolean type

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java

This bug was introduced as part of #750, and manifests itself as a stack overflow between `GenericDatabaseDialect::createColumnConverter` and `SqlServerDatabaseDialect::columConverterFor`.
In addition to this fix, this PR includes:
- A unit test that would have caught this error for every dialect
- A unit test for the new functionality added in #750 
- Refactoring the column converter override method in PostgreSqlDatabaseDialect for testing
- A unit test for Postgres-specific column converters

CC-7414: Fix SqlServer column converter infinite loop & add column converter tests

---

src/main/java/io/confluent/connect/jdbc/util/TimeZoneValidator.java

#628 mentioned specifying "Any valid JDK time zone" in the documentation.
This effects this change in the generated documentation:
```diff
-  * Valid Values: io.confluent.connect.jdbc.util.TimeZoneValidator@4c98385c
+  * Valid Values: Any valid JDK time zone
```

MINOR: Add TimeZoneValidator::toString.

---

pom.xml
src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java
src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java

This PR adds an integration test with an embedded postgres instance.
There are three tests:
1. Verify that the test setup produces OOM exceptions with large batch sizes.
2. Verify that the test setup does _not_ produce OOM exceptions with small batch sizes.
3. Verify that tables are not left locked when autoCommit is disabled. 
Test 3 addresses a side-effect of autoCommit that was called out in #466, where read-only queries with autoCommit disabled would leave open locks on the database. This test verifies that the `JdbcSourceTask` does not leave open locks from any operations.
#466 specifically observed that the TableMonitorThread would leave open locks if auto-commit was disabled on that connection. This PR circumvents that issue by leaving the TableMonitorThread connection as-is, with …

Fix Postgres OOM by limiting fetch size

---

src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

Addressing ticket CC-7637 https://confluentinc.atlassian.net/browse/CC-7637.
Before the change, a DEBUG message logged in `createPreparedStatement()` which contains the prepared statement before variable bindings.
After the change, in addition to what we already have, there is also a DEBUG message logged in `executeQuery()` right before the statement got executed. I have checked manually: this message contains all the information acquired from the bindings. Hence, there is no longer "?" in the query. 
There are two implementation of `executeQuery()`: one in `BulkTableQuerier` class, and the other in `TimestampIncrementingTableQuerier` class. I only added the new logging to `TimestampIncrementingTableQuerier`'s implementation, because for `BulkTableQuerier`'s implementation, the statement …

CC-7637: added logging of query to be executed at DEBUG level

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java

By default, the driver has no limit for timing out trying to make
a connection (https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html#setLoginTimeout(int))
This fix will set to 1 minute.
Without this fix, the connect framework may hang in the main thread (perhaps when
validating a connector config during Table Recommender), and block the entire
node's REST API. A framework-level fix is ideal, but this fix will alleviate
the issue in the short-term and on older worker versions.
Also considered making this configurable, but 1 minute is pretty conservative

CC-7628 Set conservative timeout for JDBC to stop trying to reach drive

---

src/main/java/io/confluent/connect/jdbc/sink/metadata/FieldsMetadata.java
src/test/java/io/confluent/connect/jdbc/sink/metadata/FieldsMetadataTest.java

Currently the use of a HashMap to store the columns loses the ordering of the columns from the schema.
When the create table is generated, the order of the columns is unpredictable.
This change creates a LinkedHashMap which preserves the original column order from the valueSchema and tests to check ordering is functioning correctly.

Make metadata allFields ordered consistently with the valueSchema.

---

src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java

This fix aims to address an issue that happens when the underlying connection is invalid and the JDBC driver when trying to validate the connection throws an exception instead of returning false (at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.isConnectionValid).
This behaviour caused the connector to stop, not allowing it to use the retry features inside the io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection.
Here is an example of the error (kafka connect 5.1.3):
```log
ERROR WorkerConnector{id=mssql_source_connector} Connector raised an error (org.apache.kafka.connect.runtime.WorkerConnector:92)
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: I/O Error: Connection reset
at …
```

[jdbc-source-connector] Fixed issue in CachedConnectionProvider, to enable retries when a connection is failed

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java

[JIRA](https://confluentinc.atlassian.net/browse/CC-8087)
These changes remove the logging of task configurations in plaintext, which should be done to avoid leaking database credentials and other secrets. Additionally, the log messages for whether a custom query has been specified by the user are flipped to correctly correspond to the actual presence of a custom query in the connector configuration.

CC-8087: Remove plaintext logging of task configs

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java

[Jira](https://confluentinc.atlassian.net/browse/CC-8090)
This adds a quick check to the `JdbcSourceConnectorConfig` class that ensures that the `connection.attempts` property has a value of at least one. The docs for that config property are updated accordingly, and a small unit test is added to prevent regression.

CC-8090: Validate connection.attempts property in config class

---

src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

CC-7637 was reopened because both @rhauch and @kkonstantine  believe the newly added log message should be of TRACE level. This PR is to make the change.

CC-7637: change from DEBUG level to TRACE level

---

pom.xml

Upgrades the derby to a CVE free version

MINOR: Upgrade to Derby 10.12.1.1 on versions prior to CP 5.0.x

---

pom.xml

Upgrades the derby to a CVE free version for release supporting Java 8 and newer

MINOR: Upgrade to Derby 10.14.2.0

---

licenses/LICENSE-postgresql-42.2.10.txt
pom.xml

This upgrade is backported to earlier versions in order to fix https://nvd.nist.gov/vuln/detail/CVE-2018-10936 on the postgres-jdbc driver.

MINOR: Backport upgrade to postgres jdbc to 5.0.x

---

licenses/LICENSE-postgresql-42.2.10.jre7.txt
pom.xml

This upgrade is backported to earlier versions in order to fix https://nvd.nist.gov/vuln/detail/CVE-2018-10936 on the postgres-jdbc driver.

MINOR: Backport upgrade to postgres jdbc to 4.0.x

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java

The configuration RST generated by this connector has diverged significantly from docs.
This PR makes them more similar, but not the same. Several changes were left in the docs themselves.

CC-8651: Backport docs copy-edits to config docstrings.

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/util/EnumRecommender.java
src/main/java/io/confluent/connect/jdbc/util/TableDefinition.java
src/main/java/io/confluent/connect/jdbc/util/TableType.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkConfigTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresViewIT.java
src/test/java/io/confluent/connect/jdbc/source/EmbeddedDerby.java
src/test/java/io/confluent/connect/jdbc/util/TableTypeTest.java

This change allows the JDBC sink to optionally write to tables (by default), views, or a combination. A new low-importance `table.types` configuration property has been added to the JDBC sink config, with `table` and/or `view` as allowed values, with `table` being the default to maintain backward compatibility when people upgrade. Note that the JDBC sink connector does not attempt to alter a view that does not match the sink records' schemas, and in such cases the sink connector always fails.
The changes are backward compatible (mostly through avoiding changes to signatures), so any connector that reused the JDBC sink classes should automatically work with these changes. Any connector that extends the generic dialect and should get all of the functionality for free.

CC-8823: Add support for the JDBC sink to write to views in addition to tables

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java

Instead of just keeping the exception names when a series of SQLException exceptions is thrown, keep the exceptions themselves as well within the `ConnectException`.

MINOR: Retain chain of SQLException exceptions

---

src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/sink/RecordValidator.java
src/main/java/io/confluent/connect/jdbc/util/ConfigUtils.java
src/main/java/io/confluent/connect/jdbc/util/StringUtils.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java

Added record validation that checks records key, key schema, value, and value schema to ensure that they match with the `delete.enabled` and `pk.mode` connector configuration properties.
Added unit tests that check all permutations of records with combinations of these configuration properties. Importantly, all of these unit tests were developed initially to identify the current behavior without the new validation, and thus asserted each permutation was either successfully written to a database or failed with one of the following:
* ConnectException (e.g., “PK mode for table 'dummy' is RECORD_KEY, but record key schema is missing”);
* NPEs; or
* SQLExceptions (e.g., “Values not bound to statement”)
The `ConnectException` instances are okay, and even had a relatively useful error message. …

CC-8898: Add better error messages when consumed records don’t match connector config

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTypeTest.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTypeTest.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTypeTest.java

This PR adds support for uuid columns in the `GenericDatabaseDialect`. It works by checking the classNameForType property of the ColumnDefinition. If the JDBC driver supports UUIDs, like the PostgreSQL driver does, and classNameForType of a column matches `java.util.UUID` then the `JdbcSourceConnector` reads the column value simply as a String, because Kafka Connect does not support a logical type for UUIDs at the moment: https://issues.apache.org/jira/browse/KAFKA-4353
Related issue: https://github.com/confluentinc/kafka-connect-jdbc/issues/81

Add support for uuid columns

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java

Now sanitizing any URL property that case-insensitively contains (and not just equal to) `password`. Also added a few dialect-specific tests to ensure that different dialects are sanitizing DBMS-specific properties.
Applying to 5.0.x and newer.

CC-8750: Changed the dialects to sanitize all URL properties that case-insensitively contain “password”

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/source/integration/MySQLOOMIT.java

Extra connection properties are those that are prefixed with `connection.` and that are not already predefined by the connector’s ConfigDef. These properties are added by default in the GenericDatabaseDialect, since the existing `addConnectionProperties(…)` method was not explicitly overridden by any known connector — and if any did but did not call `super. addConnectionProperties(…)`, they just wouldn’t get this feature by default.
Modified one of the MySQL integration tests to pass a connection property via the extra properties rather than via the JDBC URI.
This is to be merged/applied only in the `master` branch for inclusion in the upcoming 6.0.0 release.

CC-9567: Allow users to define extra connection properties individually rather than only through JDBC URI

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java
src/test/java/io/confluent/connect/jdbc/util/ColumnDefinitionBuilder.java
src/test/java/io/confluent/connect/jdbc/util/TableDefinitionBuilder.java

PostgreSQL is very strict about datatypes, and string literals used in `INSERT` and `UPDATE` statements must be cast to the database type if the statement is to convert/cast the literal to the column type. 
For example, consider the following table definition:
```
CREATE TABLE users (firstName TEXT, lastName TEXT, userId UUID, preferences JSON)
```
PostgreSQL rejects an insert statement such as the following:
```
INSERT INTO users (firstName, lastName, userId, preferences) 
VALUES 'Jane', 'Doe', '4eb9d40e-c9e0-4524-b242-18d182330fed', '5';
```
The third and fourth string literals must be explicitly cast to `uuid` and `json` types, respectively:
```
INSERT INTO users (firstName, lastName, userId, preferences) 
VALUES 'Jane', 'Doe', '4eb9d40e-c9e0-4524-b242-18d182330fed'::uuid, '5'::json; …
```

CC-9565: Add support for casting stringified UUIDs to `uuid` upon insert/update/upsert in PostgreSQL

---

src/main/java/io/confluent/connect/jdbc/sink/RecordValidator.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java

Vertica does not validate that fields are bound before completing a batch. This causes tombstones to be incorrectly inserted into the destination database with every column being `null`, instead of the task failing.
Use the RecordValidator framework to require a value (non-tombstone) whenever deletes are disabled.
This will throw an exception at the beginning of the write, rather than leaving this validation up to the database driver.
Because this behavior technically works for Vertica right now, it's not safe to release this behavior as a patch version. It must only be released in 6.0.0.
This is safe to roll back, as the validation will just begin passing again, and the connector will not fail.

CC-10823: Require non-tombstone records when deletes are disabled

---

src/main/java/io/confluent/connect/jdbc/dialect/SapHanaDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/SapHanaDatabaseDialectTest.java

https://github.com/confluentinc/kafka-connect-jdbc/issues/445
Get CURRENT_TIMESTAMP not working for SAP HANA JDBC because the SAP HANA Dialect does build a correct SQL statement for getting CURRENT_TIMESTAMP.

Enable CURRENT_TIMESTAMP for SAP HANA JDBC

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskConversionTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskTestBase.java

AK Date logical type expects the native Date object to be in UTC time. It complains loudly if it receives native Date from another timezone: https://github.com/apache/kafka/blob/trunk/connect/api/src/main/java/org/apache/kafka/connect/data/Date.java#L62
Parse Date in UTC timezone, ignoring the `db.timezone` specified.
Updated unittests. Verified end-to-end against postgres and mysql using IT in `connet-ksql-integration`
Targeting `5.0.x` as the timezone fix was backported very far back. Will merge the fix forward to other branches. Fix will be released with next bugfix release on perspective branches.

CC-11507: Always parse Date in UTC

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java

`statement.setObject(index, null);` is discouraged by JDBC, as per [`setObject` documentation](https://docs.oracle.com/javase/10/docs/api/java/sql/PreparedStatement.html#setObject(int,java.lang.Object)), as some dialects may not support it.
A `getSqlTypeForSchema(Schema schema)` method is added. This method can be left alone for dialects that don't need it, or overridden when required. Nothing is affected unless a dialect overrides that method.
This code has been tested together with a dialect that uses that method and provides SQL types for the different values of `schema`.
- Unit tests have been included in the dialect that use this particular method (not present in this library)
This can be included in any future release. If possible in both 6.x and 5.5.x.

Add the possibility for dialects to provide a SQL type for null values

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java

The JDBC source connector uses a `TableRecommender` for the `table.whitelist` and `table.blacklist` properties. This recommender uses the connector properties to establish a connection, and then read the accessible tables.
Unfortunately, AK's `ConfigDef` and `AbstractConfig` class only pass to each `Recommender.validValues(...)` methods the **_parsed_** configuration properties, which are only those properties that are defined with a `ConfigDef`. 
In #870 we added the ability for users to define extra properties that would be passed to the JDBC driver when connecting to the database. These extra properties are not defined by `ConfigDef` as they vary by DBMS/driver, and therefore are not included when passed to any Recommender instances. In the case of the `TableRecommender`, if the extra …

CC-11984: Remove the `table.whitelist` and `table.blacklist` recommended values

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java

The `ConfigException` class doesn't have a constructor that accepts a child exception, but it does have a constructor that appears to, which accepts [a `String` and an `Object`](https://github.com/apache/kafka/blob/149897976214a769a35cf87eecf9c02221f8d597/clients/src/main/java/org/apache/kafka/common/config/ConfigException.java#L32-L34).
Using that constructor with a message and an exception cause error messages like this to be logged:
```
Invalid value org.postgresql.util.PSQLException: FATAL: password authentication failed for user "fm_service_api_journal_usage" for configuration Couldn't open connection to jdbc:postgresql://db.my-env.local/db
```
The fix here replaces the `ConfigException` with a `ConnectException`, which should fix how errors are logged when the connector has trouble …

MINOR: Fix exception when failing to read tables

---

src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java

When use merge to upsert oracle table, if there is a long text (>=32 kb), there will be an exception "ORA-01461: can bind a LONG value only for insert into a LONG column". This happens even when the column type is CLOB. 
replace PreparedStatement.setString() with PreparedStatement.setNString() in bindMaybePrimitive(). Manually tested that this works, and have no side effect.
targeting 5.0.x; once merged, pint merge all the way to master; release a bug fix version from 5.4.x

CC-11940: fix a bug that happens when merging long text to oracle table

---

pom.xml
src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/integration/BaseConnectorIT.java
src/test/java/io/confluent/connect/jdbc/source/integration/MSSQLDateTimeIT.java
src/test/resources/log4j.properties

Ms Sql Server datetime columns have a precision error that causes our connector to loop on the most recent record. This error cannot be fixed by increasing precision because precision is set at a driver level.
http://www.dbdelta.com/sql-server-2016-and-azure-sql-database-v12-breaking-change/
We've decided to forbid the use of `datetime` for MSSQL Server (post 2016) and this pr includes a runtime validation for it
- [ x] no
Tested this using IT tests and different MS SQL Drivers locally
- [ x] Integration tests

CC-8794: MS SQL Server datetime give repeated messages due to rounding error

---

pom.xml

The plugin is included only in the standalone profile. 
Needs to be included overall

MINOR: Include maven release plugin to the right profile

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresViewIT.java

Certain errors encountered in the JDBC Sink Connector can be deferred to the DLQ for later access, e.g, a failure to bind a SinkRecord to the statement.
When encountering these errors, send the record and its corresponding error to the DLQ.
TBD

CC-9435: Implement DLQ Support in JDBC Sink

---

pom.xml
src/test/java/io/confluent/connect/jdbc/source/integration/MSSQLDateTimeIT.java

Now merged #918 included some dependencies (connect-utils, licensing-extensions) that were not available in JDBC. 
Also noted that with a current docker update, test containers used for #918 were failing
- Replaced connect utils, licensing extensions config, with raw strings, and removed the dependency
- Bumped [test containers version](https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.0-rc2)
- [ x] Unit tests
- [x ] Integration tests
Pint merge up

Remove Connect-utils and Licensing-Extensions Deps

---

pom.xml

This property was used in repository/url definition.  This causes a problem with resolution of the parent project/pom, since
property-evaluation occurs in Maven after the parent project is resolved.
Remove the property in favour of hard-coded repo URL.
Several other connector projects
- Failed Travis test build: https://travis-ci.org/github/javabrett/kafka-connect-jdbc/builds/734927879
- Passing Travis test build: https://travis-ci.org/github/javabrett/kafka-connect-jdbc/builds/734957751

Maven: Removed build property ${confluent.maven.repo}.

---

pom.xml
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java
src/test/java/io/confluent/connect/jdbc/source/integration/PauseResumeIT.java

As described in https://github.com/confluentinc/kafka-connect-jdbc/issues/374, CC-12468, and SourceTask [javadoc](https://github.com/apache/kafka/blob/trunk/connect/api/src/main/java/org/apache/kafka/connect/source/SourceTask.java#L48), `poll()` should block when no data is available, but periodically return control flow to caller to give it a chance to pause the connector. Failure to do so caused pause to not be reflected until any result was polled from the database. The workaround is to delete the connector and recreate to resume. But, it is not as convenient as pause/resume.
Keep track of consecutive empty results. Return `null` to WorkerSourceTask once consecutive empty results pass a threshold.
Other source connectors will have the same issue and may need to be updated accordingly. …

CC-12468: Periodically return control flow to WorkerSourceTask

---

src/test/java/io/confluent/connect/jdbc/source/integration/PauseResumeIT.java

The executePut method was deprecated. Using it causes a warning at compile time, failing the build.
Replace usage with requestPut.

MINOR: fix the build for 5.2.x

---

pom.xml

Bad merge caused mssql jdbc driver to accidentally be pulled into package
Change scope back to test

MINOR: fix mssql jdbc driver scope that was accidentally changed by bad merge

---

src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java

With https://github.com/confluentinc/kafka-connect-jdbc/pull/947, poll periodically returns null
Update test expectation to call poll until result not null

MINOR: fix the build for 5.5.x

---

pom.xml

Docs link is broken. Should have been caught in https://github.com/confluentinc/kafka-connect-jdbc/pull/931 as it was in https://github.com/confluentinc/kafka-connect-storage-cloud/pull/363.
Pin to a Confluent Platform version instead of the connector version for the docs link.
Put out a new 10.0.x release immediately after merging.

MINOR: Fix documentation link for Confluent Hub

---

pom.xml

Confluent Hub documentation links not redirecting properly.
Update pom.mxl with correct path to docs page

Update pom.mxl with correct path to docs page

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java

Version is showing up as `null` in logs, but just for the sink task (and not the sink connector or the source connector or task). This should fix it by using the same strategy for the sink task's `version` method that's used by the other relevant classes.

MINOR: Fix JdbcSinkTask::version

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java

The source connector did not validate topic.prefix. If there is a space in it, the connector will eventually end up with an exception, with a message totally irrelevant to the the very root cause.
Validate the config in the first place to disallow spaces in between, and automatically trim leading and tailing spaces.
targeting 5.0.x, will push to master.

CC-12626: validate topic.prefix to disallow spaces in between

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/MySqlDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java

Inaccurate log namespaces caused by `GenericDatabaseDialect` subclasses inheriting the logger from their parent. Results in logs with weird things like `PostgreSqlDatabaseDialect:571` when the Postgres dialect has, to date, only 423 lines total.
Give each database dialect its own logger.
Jenkins build.
Target 5.0.x, port forward through to master.

MINOR: Fix logger classes for dialects

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java
src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
src/test/java/io/confluent/connect/jdbc/util/CachedConnectionProviderTest.java

Currently for string value, jdbc sink always use setString() to bind, and for bytes value, always use setBytes() to bind. This is causing several escalations. Please see https://confluentinc.atlassian.net/browse/CCDB-3681 for more details.
Now choose binding method wisely according to column def. For string value, if the column def is CLOB or NCLOB, use setCharacterStream() to bind, whereas if the column def is NVARCHAR2, use setNString() to bind, otherwise use setString(); For bytes value, if the column def is BLOB, use setBlob(), otherwise use setBytes().
targeting 5.0.x, will pint merge to master.

CCDB-3681: pick binding method wisely according to column def

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java

The table monitor thread isn't used in query mode, but still runs in the background locking up database tables.
For databases with large numbers of tables this generates significant extra unproductive database load.
Only start the table monitor thread when the query config is empty.
All other call sites are safe to execute on the not-running thread, and avoids multiple nullchecks.
This targets 10.0.x, since this is the first version which does not have the TableRecommender in use.

CCDB-3732: Disable table monitor thread when in query mode

---

src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/main/java/io/confluent/connect/jdbc/sink/SchemaMismatchException.java
src/main/java/io/confluent/connect/jdbc/sink/TableAlterOrCreateException.java
src/main/java/io/confluent/connect/jdbc/sink/metadata/FieldsMetadata.java
src/test/java/io/confluent/connect/jdbc/integration/BaseConnectorIT.java
src/test/java/io/confluent/connect/jdbc/sink/DbStructureTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresViewIT.java

Certain errors encountered in the JDBC Sink Connector can be deferred to the error reporter for later access, e.g, a failure to bind a SinkRecord to the statement.
When encountering these errors, send the record and its corresponding error to the error reporter.
Other connectors that may want error reporting.
Backport to 10.0.x

CCDB-192: Implement Error Reporting Support in JDBC Sink

---

pom.xml

https://snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-571481
Upgrade org.postgresql:postgresql to version 42.2.19

Upgrade org.postgresql:postgresql to version 42.2.19

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkConfigTest.java

Without validation, a configuration with empty `table.name.format` is allowed to create the connector but fails later on in writer with exception `Destination table name for topic 'redacted' is empty using the format string ''`
Add non-empty string validation to the configdef.
Added unittest in `JdbcSinkConfigTest`
Included in bugfix release of `10.0.x` and going forward.

MINOR: Add validation that `table.name.format` is non-empty

---

src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

Typo in the method names of the interface CriteriaValues.
Change the method names in the interface and the implementations
- [ x] no
Merging to master.
No functionality change for the kafka-connect-jdbc connector

fix typo in the method names of the interface CriteriaValues

---

pom.xml

The current version of Postgres driver 42.2.10 is impacted by CVE-2020-13692.
Upgrade Postgres driver version. This fix is already applied in 5.2.x, 5.3.x, 5.4.x, 5.5.x, and master.

Upgrade Postgres driver to fix CVE.

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTypeTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskConversionTest.java

We currently have precision available to us, but we don't add it to the Connect Schema.  This one-line change adds the precision.

FF-5018: JDBC Source Connector needs to provide column precision for DECIMAL (NUMERIC) data types

---

pom.xml

Vulnerabilities with below versions as reported by twist lock
org.apache.zookeeper_zookeeper 3.4.13-- Please upgrade to the latest version listed in the following CVEs 
io.netty_netty 3.10.6.Final-- Please upgrade to the latest version listed in the following CVEs 
Explicitly mark the ZK dependencies as `test`. common pom defines them in dependency management and hence they are marked as `compile` by maven and included in the final package.

CC-14541 : Exclude zk and netty from packaging

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java

Removed in https://github.com/confluentinc/kafka-connect-jdbc/pull/930, accidentally re-introduced in https://github.com/confluentinc/kafka-connect-jdbc/pull/990.

MINOR: Remove unused TableRecommender class

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java

There is a possibility for an NPE to happen if the DDL statements happen without an exception, but describe/get table returns null in the database.  Generally RDS guarantees DDLs are consistent with the get but we've encountered a database where this happens. 
Add more null checks before and after `amendIfNecessary ` 
- [x ] Unit tests
Pint merge up

CCDB-3981: Add a null check for get after auto create for JDBC connector

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingOffset.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingOffsetTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerierTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampTableQuerierTest.java

[Jira](https://confluentinc.atlassian.net/browse/CCDB-4141)
Data loss can occur in timestamp mode when there are multiple rows with the same timestamp if the connector is shut down after reading at least one such row but before reading all of them.
Take a more conservative approach with the timestamps we use for the source offsets in records produced by the connector. These timestamps will now only advance once the connector has either:
- Read every row from the current query that uses a given timestamp
OR
- Read every row from the current query
For example, if the connector's current timestamp is T0 and it then reads five rows from the current query with timestamps T1, T1, T2, T2, and T3, the records it produces will have timestamps of T0, T1, T1, T2, and T3, respectively. Put visually: …

CCDB-4141: Prevent data loss in timestamp mode

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java

`GenericDatabaseDialect::applyDdlStatements` just does a `statement.executeUpdate` on the ddl statements to execute them, without explicitly calling `commit` to ensure they are committed. At the same time, the `CachedConnectionProvider` acquired from `JdbcDbWriter::connectionProvider` explicitly disables autocommit on the connection. The combination of this means that DDL changes may not be COMMITed to the DB before our next query.
Explicitly call `commit` on the connection to commit the DDL changes. From the `Connection::setAutoCommit` javadoc:
>  If a connection is in auto-commit mode, then all its SQL statements will be executed and committed as individual transactions. Otherwise, its SQL statements are grouped into transactions that are terminated by a call to either the method commit …

CCDB-4190: Commit after DDL

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java

Some `SQLException`s are non-transient and should result in failing the task rather than log and continue.
Explicitly catch and rethrow `SQLNonTransientException` wrapped in a `ConnectException`
New unittest was added
Bugfix to be taken back to `10.0.x`

CCDB-4193: Terminate task on SQLNonTransientException

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java

Since KAFKA-10792 fixed the source task `stop()` to be called on the task thread, the previous assumption that `stop()` will be called in a separate thread is no longer correct. Instead, the shutdown steps should be done in the `stop()` method directly. This method will be called by framework on the same task thread as `poll()` , once `poll()` relinquishes control back to framework.
Detect whether `stop()` is called from task thread. If so, do shutdown immediately.
Unit test expectation was updated
Since KAFKA-10792 was taken back to `2.5` , we similarly take this change back to `5.5.x` .

CCDB-4247: Close resources correctly on stop

---

Jenkinsfile

All `5.0.x`+ builds failing with 
```
01:33:34  [2021-09-04 08:33:34,264] ERROR mysql: /tmp/MariaDB4j/base/bin/mysql: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory (ch.vorburger.exec.ManagedProcess:71)
```
Root cause is https://github.com/confluentinc/jenkins-common/pull/373/files changing the default jenkins node to `docker-debian-10-jdk8` , which likely does not have `libncurses` package installed. Change it back to previous label we were using - `docker-oraclejdk8`
Other connectors either already have specified nodeLabel `docker-oraclejdk8` or are fine building with the new `docker-debian-10-jdk8` image.
Rely on PR builder to run in Jenkins

MINOR: fix the build

---

src/main/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java

With the current merge query, user will hit the following SQL exception.
```
WARN Write of 1 records failed, remainingRetries=10 (io.confluent.connect.jdbc.sink.JdbcSinkTask:92)
java.sql.BatchUpdateException: Incorrect syntax near the keyword 'with'.
```
According to the [docs](https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc00938.1570/html/locking/locking103.htm), Sybase does support HOLDLOCK syntax directly after table name. But appending HOLDLOCK to the table name also fails in the case of merge. While the [documentation for merge command](https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36272.1600/doc/html/san1393051041603.html) did not mention HOLDLOCK at all.
The other problem is that the driver also complains about the trailing …

Fix Sybase dialect upsert syntax

---

src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java

Previous commit missed two test cases.
https://github.com/confluentinc/kafka-connect-jdbc/pull/1112
Remove holdlock and semicolon from upsert statement in tests.

Remove holdlock from test code.

---

src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java

Performance regression when writing short strings into CLOB type columns
Call the `setCharacterStream` and `setNCharacterStream` variants that take the length of the stream as argument. These variants can use the length to determine the most efficient binding to use. From javadoc:
> Consult your JDBC driver documentation to determine if it might be more efficient to use a version of setCharacterStream which takes a length parameter.
Unit tests were updated. Manually verified performance regression fixed.
Backport fix all the way back to `5.0.x` when #1004 introduced this logic.

MINOR: call `setCharacterStream` API with length

---

src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/util/LRUCache.java
src/main/java/io/confluent/connect/jdbc/util/LruCache.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java

Copied from [Jira](https://confluentinc.atlassian.net/browse/CCDB-4470):
When run in timestamp or timestamp+incrementing mode against a given table, the JDBC connector will:
1. Issue a SELECT query that uses the user-supplied timestamp column name in a WHERE clause via JDBC and track the ResultSet for that query
2. Use the ResultSetMetadata from that query's ResultSet to construct a Kafka Connect schema for the source records that will be produced for that query
3. Iterate over each row in the ResultSet and, for each row, construct a Kafka Connect Struct that will be used as the value for the source record corresponding to that row
4. Extract the values for each timestamp column from that struct using the user-supplied timestamp column names
This can cause issues when the logic of the …

CCDB-4470: Handle case mismatch between user-specified and table-provided timestamp column names

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java

[Jira](https://confluentinc.atlassian.net/browse/CCDB-4454), [GitHub issue](https://github.com/confluentinc/kafka-connect-jdbc/issues/675)
When a table is created in PostgreSQL, if its name exceeds the maximum permitted length (see https://www.postgresql.org/docs/14/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS), it will be truncated automatically. For example, a table named "toolongtoolong" would be truncated to "too" if the maximum permitted length were 3 bytes.
Unfortunately, this truncation does not take place automatically when the connector checks to see if a table exists, so even if the connector is able to successfully create a table, if the name was truncated during that creation, the next time the connector checks to see if the table exists, it will appear as if the table is …

CCDB-4454: Automatically truncate long table names to respect PostgreSQL length limits

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/source/TableMonitorThreadTest.java

[Jira](https://confluentinc.atlassian.net/browse/CCDB-4476), [GitHub issue](https://github.com/confluentinc/kafka-connect-jdbc/issues/1142)
The connector can block in its `taskConfigs` method while [invoking `tableMonitorThread::tables`](https://github.com/confluentinc/kafka-connect-jdbc/blob/26cc0b1e309f15f368fbf6d2cd6c8665770c1608/src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java#L149), which is [synchronized](https://github.com/confluentinc/kafka-connect-jdbc/blob/26cc0b1e309f15f368fbf6d2cd6c8665770c1608/src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java#L96) and therefore blocks on the completion of any pending calls to the [also-synchronized `updateTables` method](https://github.com/confluentinc/kafka-connect-jdbc/blob/26cc0b1e309f15f368fbf6d2cd6c866 …

CCDB-4476: Prevent blocking on database connection in JdbcSourceConnector::taskConfigs

---

src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java

This reverts commit b33ed0572430457dcaa9054c2009589a59847442.
IT added in https://github.com/confluentinc/kafka-connect-jdbc/pull/1147 has reproduced a regression introduced by #1130
Revert this PR

Revert "MINOR: call `setCharacterStream` API with length (#1130)"

---

pom.xml
src/test/java/io/confluent/connect/jdbc/sink/integration/OracleDatatypeIT.java

We do not have integration tests for Oracle dialect
This PR introduces IT for Oracle dialect to iterate through common primitive and logical types and short and long strings.
This is a test only change

MINOR: Adds IT to test oracle data type bindings for sink connector

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/test/java/io/confluent/connect/jdbc/source/TableQuerierTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerierTest.java
src/test/java/io/confluent/connect/jdbc/source/TimestampTableQuerierTest.java
src/test/java/io/confluent/connect/jdbc/util/DateTimeUtilsTest.java

Background
Oracle DB stores a timestamp with microseconds granularity. The JDBC connector produces events that have the same timestamps when the connector rounds up timestamp to milliseconds, causing downstream applications not to sort events properly and not to be able to compare records with higher precision. 
Adding micros and millis format negatively impacts the rollout as the offset management becomes backward-incompatible due to loss of precision. So we will have three new config types,
- `connect_logical` (default)
- `nanos_long` (nanos is epoch as Int64)
- `nanos_string` (nanos is epoch as String)
- `nanos_iso_datetime_string` (`yyyy-MM-dd'T'HH:mm:ss.n` for eg., `2022-01-05T12:07:56.702041000`)
We also discussed not allowing the customers to define the iso string format as it …

CCDB-4340 - Add support for the new Timestamp granularity features in the jdbc source connector

---

pom.xml

On `master`, the POM `<version>` should always end in `.0-SNAPSHOT`. On all `.x` branches, the POM `<version>` should always end in `.r-SNAPSHOT`, where `r` is the patch version number of the latest release from that branch, plus one (i.e., if the latest release on the `8.9.x` branch is `8.9.3`, the POM `<version>` should end in `.4-SNAPSHOT`).
This PR corrects the version on the `10.3.x` branch.
NOTE: This should not be propagated forward via `pint merge` as that would overwrite the development version on the master branch, which is correct as-is. As a result, I've added `[ci skip]` to the PR title to disable automatic invocation of `pint merge`.

[ci skip] MINOR: Fix snapshot version

---

pom.xml

pom for `10.3.x` was created incorrectly with version `10.3.x-SNAPSHOT` instead of `10.3.0-SNAPSHOT`
Fix the pom
Cut release for `10.3.0`

MINOR: Fix version and tag for 10.3.x branch

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java
src/test/java/io/confluent/connect/jdbc/util/DateTimeUtilsTest.java

For timestamp columns that are optional, the values appear as `null`. When the `timestamp.granularity` config is selected to be `nanos_long` or `nanos_string` or `nanos_iso_datetime_string` this is currently not handled properly and results in NPE
This is now handled by the connector

CCDB-4340 Fix the NPE on timestamp columns that are null

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java

[Jira](https://confluentinc.atlassian.net/browse/CCDB-4512), [GitHub issue](https://github.com/confluentinc/kafka-connect-jdbc/issues/480)
The Postgres JDBC driver we use returns a scale and precision of zero for `NUMERIC` and `DECIMAL` columns that do not have a fixed precision and scale defined. However, the [Postgres spec](https://www.postgresql.org/docs/13/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL) indicates that a column defined without a fixed precision or scale can contain values with non-zero scale and (obviously) non-zero precision.
This causes issues when we invoke [`ResultSet::getBigDecimal`](https://github.com/confluentinc/kafka-connect-jdbc/blob/fe850317e48c6cc5da2e8c3d5c77bc4c12ba9653/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1357) …

CCDB-4512: Fix handling of PostgreSQL NUMERIC/DECIMAL types with unspecified scale

---

src/main/java/io/confluent/connect/jdbc/JdbcSinkConnector.java
src/test/java/io/confluent/connect/jdbc/JdbcSinkConnectorTest.java

Misconfigured `pk.mode` and `delete.enabled` combination should not be surfaced by throwing an exception when the connector or task starts. Instead, the connector should notify the user that it is configured incorrectly via the Connector::validate method.
Do cross-fields configuration validation in `Connector::validate` method, utilizing existing logic from [PrimaryKeyModeRecommender](https://github.com/confluentinc/kafka-connect-jdbc/blob/348e49f4a93261dd7b1365f469af426fa9ee8c6c/src/main/java/io/confluent/connect/jdbc/util/PrimaryKeyModeRecommender.java#L41).
Ref:
1. [How to Write a Connector for Kafka Connect](https://www.confluent.io/blog/write-a-kafka-connect-connector-with-configuration-handling/)
2. [kafka-connect-elasticsearch](https://github.com/confluentinc/kafka-connect-elasticse …

CCDB-4354: preflight cross-fields validation for configuration PK_MODE

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java
src/test/java/io/confluent/connect/jdbc/util/DateTimeUtilsTest.java

The old iso date format `yyyy-MM-dd'T'HH:mm:ss.n` did not format nanos properly
```
jshell> DateTimeFormatter ISO_DATE_TIME_NANOS_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.n");
jshell> var t= Timestamp.from(java.time.Instant.now())
t ==> 2022-01-26 11:43:39.669414
jshell> t.getNanos()
$10 ==> 669414000
jshell> t.toLocalDateTime().format(ISO_DATE_TIME_NANOS_FORMAT);
$11 ==> "2022-01-26T11:43:39.669414000"
jshell> t.setNanos(0)
jshell> t.toLocalDateTime().format(ISO_DATE_TIME_NANOS_FORMAT);
$13 ==> "2022-01-26T11:43:39.0"
jshell> t.setNanos(001)
jshell> t.toLocalDateTime().format(ISO_DATE_TIME_NANOS_FORMAT);
$15 ==> "2022-01-26T11:43:39.1"
```
The format stips the leading and trailing 0s making it result in a Timestamp with invalid precision
Change the format to …

Improve the iso date time format to have better nanos precision

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java

If there's no table found in the TableMonitorThread, we currently just don't spawn any tasks. While this is reasonable behavior, it makes debugging these issues a little bit harder since we see a connector running but no tasks. 
We should aim to instead spawn tasks regardless of the table compatibility but immediately fail them to represent this misconfiguration.

Spawn Tasks even when there's no tables that match the include/exclude list.

---

pom.xml
src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java

Customers want the ability to set transaction isolation for queries.  Ansi-sql supports `READ_UNCOMMITTED `, `READ_COMMITTED`, `REPEATABLE_READ`, `SERIALIZABLE`.  We want to set the infrastructure to support custom db specific isolation modes as well. For version 1, we're supporting `SQL_SERVER_SNAPSHOT_ISOLATION` for Sql Server as well.
Provide a config to set an isolation mode. We implement the isolation mode setting in the dialect classes to allow specific dbs to override the generic implementation and set custom isolation modes.
Note that we still gate keep which isolation modes are supported by limiting the `TransactionIsolationMode` enum (internal to the config class). However we are able to expand on this model and set isolation …

CCDB-4586: Request to add a `Prefix` or a `Snapshot` mode for JDBC Source Connector to execute the query in snapshot mode

---

pom.xml

Fix https://github.com/advisories/GHSA-673j-qm5f-xpv8
Upgrade postgres driver to 42.3.3
Backport to 10.0.x

CCDB-4600: Upgrade postgres to 42.3.3 for jdbc, postgres cdc connectors

---

pom.xml

https://github.com/confluentinc/kafka-connect-jdbc/pull/1169 moved the `mssql-jdbc` driver to the `provided` dependency from the `runtime` dependency. This led to the driver not being packaged in the connector package as it was in the older versions say `10.2.x`
Add back the dependency as compile-time so that it's packaged:
```
❯ ls target/kafka-connect-jdbc-10.4.0-package/share/java/kafka-connect-jdbc
checker-qual-3.5.0.jar         kafka-connect-jdbc-10.4.0.jar  ojdbc8-production-19.7.0.0.pom orai18n-19.7.0.0.jar           postgresql-42.3.3.jar          sqlite-jdbc-3.25.2.jar         xmlparserv2-19.7.0.0.jar
common-utils-6.0.0.jar         mssql-jdbc-8.4.1.jre8.jar      ons-19.7.0.0.jar               osdt_cert-19.7.0.0.jar         simplefan-19.7.0.0.jar         ucp-19.7.0.0.jar …
```

[MINOR] Fix missing msssql driver in v10.4.0

---

src/main/java/io/confluent/connect/jdbc/source/BulkTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java

RCCA-5813 discovered that there is DEBUG logging present in the JDBC connector that logs query contents.
Demote the logging from DEBUG to TRACE.
Backport to 10.0.x

CCDB-4692: [JDBC Connector] Demote logging containing query contents from DEBUG to TRACE

---

pom.xml

Backporting [CCDB-4600](https://confluentinc.atlassian.net/browse/CCDB-4600) - https://github.com/confluentinc/kafka-connect-jdbc/pull/1182
Upgrade driver to 42.3.3
Backport to 5.4.x

Backport CCDB-4600 to 5.4.x

---

pom.xml

The maven release:branch command ran partially i.e. created the 1.5.x branch but did not update the POM.
Making the POM changes manually.
- [x ] no
- [x ] Unit tests

CCDB-4777: Fixing POM as maven release:branch command failed

---

src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/MicrosoftSqlServerSinkIT.java

A sink that sends a null `BYTES` value to SQL Server will throw a `java.sql.BatchUpdateException` with reason "Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query."
This is the problem described in issue #1138.
Provide an explicit SQL type for null `BYTES` values in `SqlServerDatabaseDialect.getSqlTypeForSchema()`.
?

fix null BYTES value insert/upsert for SQL Server

---

pom.xml

The migration from log4j to reload4j was not done for this repository. As a result it was failing builds with the deprecated dependencies.
Replaced with new dependencies.
pint-merge to other branches.

CCDB 5027 migrate log4j to reload4j

---

pom.xml

logredactor is not necessarily required as per this:
https://confluentinc.atlassian.net/wiki/spaces/~913794610/pages/2772764716/Backport+reload4j+to+replace+Confluent-log4j
Replaced it with ch.qos.reload4j.reload4j

CCDB 5027 Replaced logredactor

---

pom.xml

The branches above 10.0.x don't get the reload4j version from the common parent.
Manually fixed the version.
Will pint merge to further branches.

Added reload4j version

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java

- https://confluentinc.atlassian.net/browse/MMA-11946
When trying to create a JDBC source connector in C3, it returns missing required configuration "connection.url" which has no default value. but we can see the "connection.url" is defined. 
Even though this is a C3 UI bug, customer was not able to upgrade confluent platform to 7.1.1 because they are seeing that tasks fails with the same exception - `org.apache.kafka.common.config.ConfigException: Missing required configuration "connection.url" which has no default value` when they upgrade to 7.1.1. More details in this thread - https://confluent.slack.com/archives/C03NGEF6GTD/p1657710853069849
- I was able to find the reason why connector task was failing when customer try to upgrade to v7.1.1. This is due to a recent  bug fix in kafka …

RCCA-7885,MMA-11946: Add default value for Connection URL config and remove redundant code

---

.gitignore
pom.xml
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/util/TableType.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkConfigTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresPartitionedIT.java
src/test/java/io/confluent/connect/jdbc/util/TableTypeTest.java

Postgres partitioned tables are not supported [after this change in the driver](https://github.com/pgjdbc/pgjdbc/commit/25eb32c8681eaa4aaac801808b6028e9f5dfbea8#diff-0571f8ac3385a7f7bb34e5c77f8afd24810311506989379c2e85c6c16eea6ce4L1287).
#1092
Map `PARTITIONED TABLE` as a valid value;
not yet enabled by default, although that could be added still.
? Merge to master I guess; no plans for backports unless specifically requested.

Support Postgres partitioned table #1092

---

src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/integration/MicrosoftSqlServerSinkIT.java

The JDBC sink connector when used with SqlServer, observes performance degradation due to passing of string query parameters in unicode format. 
The recommended approach is to use `setStringParametersAsUnicode=false` when using non-unicode data types such as CHAR, VARCHAR, LONGVARCHAR JDBC types.
However, if unicode data types such as NCHAR, NVARCHAR, LONGNVARCHAR are used, the application should use national character methods such as setNString, setNCharacterStream etc. Otherwise, it could lead to data loss.

RCCA 7749 Use national character methods for unicode strings

---

src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java
src/test/java/io/confluent/connect/jdbc/source/EmbeddedDerby.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java

https://confluentinc.atlassian.net/browse/CCDB-5069
#1093 provided a fix to avoid data loss, in Timestamp Query mode, when we have multiple rows with the same timestamp in the DB if the connector is shut down after reading at least one such row but before reading all of them. This fix however failed to capture the case in-memory offsets that are used when the connector faces a connectivity error and goes into a retry when the DB has a network partition.
Going back to the example used in #1093 -- if the connector's current timestamp is T0 and it then reads five rows from the current query with timestamps R1(T1), R2(T1), R3(T2), R4(T2), and R5(T3), the records it produces will have timestamps of T0, T1, T1, T2, and T3, respectively. In this case, if the connector sees a transient …

CCDB-5069: Fix data loss in timestamp mode due to in-mem offsets

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/main/java/io/confluent/connect/jdbc/util/LogUtil.java
src/test/java/io/confluent/connect/jdbc/util/LogUtilTest.java

For PostgresDB; a BatchUpdateException might contain sensitive data.
Trimming the sensitive data off BatchUpdateException.
NA

CCDB-5222: For JDBC Sink connector; removing sensitive data from BatchUpdateException.

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/test/java/io/confluent/connect/jdbc/util/LogUtilTest.java

#1266 added a feature to trim sensitive data, but it missed hadling individual exceptions and only handled Nested
Trim sensitive data before iterating over the individual exceptions

[MINOR] Fix sensitive data trimming from exceptions

---

src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java
src/test/java/io/confluent/connect/jdbc/util/CachedConnectionProviderTest.java

Reverts confluentinc/kafka-connect-jdbc#1206
We missed a big part of the fact that the internal retries of the ConnectionProvider also call on `close`.
For example, [JdbcDbWriter#closeQuitely](https://github.com/confluentinc/kafka-connect-jdbc/blob/5.0.x/src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java#L79) is called during internal retries [JdbcSinkTask#put](https://github.com/confluentinc/kafka-connect-jdbc/blob/5.0.x/src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java#L104). This can cause NPEs as we return a null connection back when a new connection is requested since we have set `isRunning` to false. 
This regression wasn't caught by 5.0.x tests. It failed further down on the pint merge on newer branches.

Revert "Allow close() on CachedConnectionProvider while attempting to connect…"

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java

In confluent cloud if someone manually deletes the DB table while the JDBC connector is running, the connector will start failing even if **auto.create** config is set as true. Ideally when auto create is true table should be created again. This happens because the connector maintains a cache for for the tables and if a table is deleted that cache becomes invalid and no new table is created till process restarts.
Reinitialise the writer object when the connector goes into final retry state. This resets the cache and the table is created again.
Added integration test for the scenario.
Bug fix for mainly confluent cloud releasing to latest version of connector.

[CCDB-5238] Reinitialize writer object during retry to refresh cache to clear invalid state

---

src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java

Log message is slightly confusing. We don't acquire a lock on reads.
Changed the log message.

Fixing log message

---

src/main/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java

When trying to insert a record with null field into Sybase DB (with jtds driver), in some cases the connector was failing with the following exception:
```
Write of 1 records failed, remainingRetries=1 (io.confluent.connect.jdbc.sink.JdbcSinkTask)
java.sql.BatchUpdateException: Implicit conversion from datatype 'VARCHAR' to 'TINYINT' is not allowed.  Use the CONVERT function to run this query.
at net.sourceforge.jtds.jdbc.JtdsStatement.executeBatch(JtdsStatement.java:1069)
at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:196)
at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:186)
at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:80)
at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84) …
```

RCCA-100001: fix null field issue with sybase dialect

---

src/test/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialectTest.java

Test for Null binding was failing for SybaseDialect.
Fixed the test.
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.confluent.connect.jdbc.dialect.SybaseDatabaseDialectTest
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.72 s - in io.confluent.connect.jdbc.dialect.SybaseDatabaseDialectTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.049 s
```

Fixed tests

---

src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java

[CCDB-5302](https://confluentinc.atlassian.net/browse/CCDB-5302?atlOrigin=eyJpIjoiY2IxNjM4YzU1MDM1NDBiMTk1YjRjMjc0NzA3MmY0Y2QiLCJwIjoiaiJ9)
Writes to CLOB datatype columns were performing extremely poorly
Issue was caused by how oracle driver was binding the insert value. If length parameter is not passed to setCharacterStream method then the driver does LOB binding by default which is the slowest form. By passing the length parameter, the driver picks the most appropriate form of binding based on length.
One exception to this is the UPSERT mode which uses MERGE statement. In that case the driver does not handle the binding correctly and requires LOB binding for all values above length 4000. This issue is further described in this …

[CCDB-5302] Added length parameter to setCharacterStream for oracle database CLOB column

---

pom.xml

Vulnerable dependency "postgresql" for kafka-connect-jdbc
CVE: https://confluentinc.atlassian.net/browse/CCDB-5300
Upgrade postgresql to 42.4.3 as per [here](https://mvnrepository.com/artifact/org.postgresql/postgresql).
Checked that postgresql 42.4.x is available from branch 5.0.x onwards
Will do ping merge after PR merge
`mvn dependency:tree` output
```
[INFO] +- org.xerial:sqlite-jdbc:jar:3.25.2:runtime
[INFO] +- org.postgresql:postgresql:jar:42.4.3:runtime
[INFO] |  \- org.checkerframework:checker-qual:jar:3.5.0:runtime
[INFO] +- com.oracle.database.jdbc:ojdbc8-production:pom:19.7.0.0:runtime
[INFO] |  +- com.oracle.database.jdbc:ojdbc8:jar:19.7.0.0:runtime
```
[CCDB-5300]: https://confluentinc.atlassian.net/browse/CCDB-5300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

[CCDB-5300] Upgrade postgresql to 42.4.3

---

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java

Reverts changes done in [CCDB-5222](https://confluentinc.atlassian.net/browse/CCDB-5222)
Find more details on why this is being done [here] (https://confluent.slack.com/archives/C04JV6U2HU2)
[CCDB-5222]: https://confluentinc.atlassian.net/browse/CCDB-5222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds config to conditionally mask SQL statements

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java
src/test/java/io/confluent/connect/jdbc/util/CachedConnectionProviderTest.java

Fixes #1205. Follows up on #1206 to fix the issue on non life-cycle events
While CacheConenctionProvider is trying to get a connection, it is impossible to stop.
Add a flag to not go on with connection attempt when a close request has been issued.
merge to 5.0.x and further

CCDB-5077: Fix closin CacheConnectionProvider to close on lifecycle events

---

src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java

JdbcSourceTaskLifecycleTests were failing due to a change to API introduced as part of #1284

[Minor] Fix upstream tests failing due to #1284

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java

[CC-19080](https://confluentinc.atlassian.net/browse/CC-19080): Fix JDBC Source Connector to support Sybase jConnect JDBC 4 Driver.
The types as returned by `Connection.getMetaData().getTableTypes().getString(int columnIndex)` for Sybase jConnect driver contains extra whitespaces at the end which causes other APIs to fail when those returned values are used as-it-is:
- "TABLE" => "TABLE     "
- "SYSTEM TABLE" => "SYSTEM TABLE "
- "VIEW" => "VIEW     "
Trimming the returned values of the aforementioned getTableTypes method. Here is the [reference](https://github.com/ManasjyotiSharma/kafka-connect-jdbc/commit/2d244549b360d4be07c6e135503115a84f1b9b3c) to the previous code change which was tested to be working fine for the jConnect driver.
NA
[CC-19080]: …

CC-19080: Fix JDBC Source Connector to support Sybase jConnect JDBC 4 Driver

---

src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java

The method name was confusing. We are only calling the commit method inside releaseLocksQuietly. Releasing the acquired locks is a side-effect of commit call.
Renamed the method to commitQuietly.

Rename method releaseLocksQuietly to commitQuietly

---

src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkConfigTest.java

Using "with (HOLDLOCK)" when performing a MERGE INTO statement in MS SQL Server in certain cases brings up performance issues (https://sqlsunday.com/2021/05/04/how-merge-can-deadlock-you/).
The HOLDLOCK is currently hardcoded into the SQL statement of the Sink connector [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java#L327) and cannot be disabled without having a custom JDBC connector.
This PR introduces a configuration option (`mssql.use.merge.holdlock`) that allows to enable/disable the use of HOLDLOCK in the MERGE statement. The default is `true`, meaning this PR should be backwards compatible.
NOTE: the unit tests had to be updated, as the JDBCSourceConfig was used everywhere, even when …

Introduce option to enable/disable HOLDLOCK when using MERGE INTO in MS SQL Server

---

pom.xml

[CC-19887](https://confluentinc.atlassian.net/browse/CC-19887): Remove non-binary file (.pom file) from the lib folder of JDBC connector.
The dependency "ojdbc8-production" of type pom is a shorthand but it add itself as a dependency (i.e. the pom ojdbc8-production-19.7.0.0.pom itself is packaged). So instead of that shorthand; depending on the actual jar deps. See [this](https://www.oracle.com/database/technologies/maven-central-guide.html) for context.
IT, UT
[CC-19887]: https://confluentinc.atlassian.net/browse/CC-19887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CC-19887: Getting rid of ojdbc8-production-19.7.0.0.pom

---

pom.xml
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java

See these for refs:
https://github.com/confluentinc/kafka-connect-jdbc/pull/1322
https://github.com/confluentinc/kafka-connect-jdbc/pull/1323
W.r.t https://confluentinc.atlassian.net/browse/CC-19797; fixing display message
W.r.t https://confluentinc.atlassian.net/browse/CC-19887; reverting the previous fix (as FOSSA is incorrectly flagging error - [ref](https://app.fossa.com/projects/git%2Bgithub.com%2Fconfluentinc%2Fkafka-connect-jdbc/refs/branch/master/45b6a8a4868289c41fe0a188278e01f47f4459d3/issues/licensing?page=1&count=20&sort=created_at_desc&status=active&filter%5Btype%5D%5B0%5D=unlicensed_dependency&revisionScanId=38358462))

CC-19887 & CC-19797: Reverting ORA dependencies due to false FOSSA license alart & Updating holdlock UI message.

---

pom.xml

[CC-20628](https://confluentinc.atlassian.net/browse/CC-20628)
RCE vulnerability in SQLITE jdbc package
Upgrade package version to 3.41.2.2.
This PR was already created by Jan [here](https://github.com/confluentinc/kafka-connect-jdbc/pull/1344) but it was for 10.6.x. Seeing how many customers use older versions as well and this is a critical vulnerability, I created this PR to target older branch 10.0.x
kafka-docker-playground doesn't have sqlite option available. Ran connector locally in both sink and source mode for sqlite with basic configs to test.
[CC-20628]: https://confluentinc.atlassian.net/browse/CC-20628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CC-20628] Updated sqlite dependency to CVE-2023-32697 to RCE vulnerability

---

pom.xml
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java
src/test/java/io/confluent/connect/jdbc/sink/integration/OracleDatatypeIT.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java

[CCDB-2031](https://confluentinc.atlassian.net/browse/CCDB-2031)
When a user has configured the `quote.sql.identifiers` property to `NEVER`, then current implementation of the connector does not honor it in all cases. Method calls which build the SQL statement in code are using the `ExpressionBuilder` class to correctly quote the table names. However, method calls that directly invoke a jdbc method with the table name do not take this into account. They are case sensitive
Overrided parseTableIdentifier method for oracle and postgres dialect, to check for config value and make the whole table name uppercase in case of Oracle and lowercase in case of Postgres.
Note: This issue might be prevalent in other dialects as well but this PR is only addressing these 2 dialects for now.
Also bumped …

[CCDB-2031] Fix quote.sql.identifiers=never not working for Oracle and Postgres

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
src/test/java/io/confluent/connect/jdbc/source/integration/PauseResumeIT.java

Ref: [CC-24497](https://confluentinc.atlassian.net/browse/CC-24497)
Added a check that sees if column names supplied as part of configuration do exist in at least one table. This prevents misuse of these configuration which can be used for SQL injection.
[CC-24497]: https://confluentinc.atlassian.net/browse/CC-24497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CC-24497] Added validation for column check

---

pom.xml
src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java

[CC-25311](https://confluentinc.atlassian.net/browse/CC-25311)
Bumped postgres driver version from 42.4.3 -> 42.4.4
[CC-25311]: https://confluentinc.atlassian.net/browse/CC-25311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CC-25311] Bump postgres driver version to 42.4.4

---

pom.xml
src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java

CC-25569: add schema and catalog info to the TableID object
Raised from base PR. Check here for the discussion - https://github.com/confluentinc/airlock-kafka-connect-jdbc/pull/2

CC-25569: add schema and catalog info to the TableID object

---

pom.xml

Task is failing due to this
https://semaphore.ci.confluent.io/jobs/90e578c1-b76a-47ea-b23d-f8955c4b92d9
This is probably because with the pom update in the recent commits, it is requiring this to be specified as well
Added `distributionManagement` tag to pom.

Add repository distribution

---

pom.xml

Use the same version as [elasticsearchsink](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/88c669db8d3b324265c0418e879fade5bf849693/pom.xml#L8). ie. `7.0.12`.
I have confirmed using the effective pom that the distributionManagement comes from the common in case of `7.0.12` but for some reason it is not there in `7.0.15-20`.
Also the `dependency.check.skip` is true as well in the `7.0.12`.
Job was failing with this.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project kafka-connect-jdbc: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace …
```

Change common pom

---

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/util/BasicJdbcCredentials.java
src/main/java/io/confluent/connect/jdbc/util/DefaultJdbcCredentialsProvider.java
src/main/java/io/confluent/connect/jdbc/util/JdbcCredentials.java
src/main/java/io/confluent/connect/jdbc/util/JdbcCredentialsProvider.java
src/main/java/io/confluent/connect/jdbc/util/JdbcCredentialsProviderValidator.java
src/main/java/io/confluent/connect/jdbc/util/StringUtils.java
src/test/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialectTest.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkConfigTest.java
src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java
src/test/java/io/confluent/connect/jdbc/util/DefaultJdbcCredentialsProviderTest.java
src/test/java/io/confluent/connect/jdbc/util/TestConfigurableJdbcCredentialsProvider.java
src/test/java/io/confluent/connect/jdbc/util/TestRefreshJdbcCredentialsProvider.java

- Add support to configure Custom Credentials Provider Class in the connector to fetch database credentials. 
- Currently to update db credentials, users needs to manually update the credential configs which leads to connector restart or incase they are using ConfigProviders -> require a restart to pull in new credentials. 
- Introducing the following interfaces in connector which users can use to implement their custom class. 
```
public interface JdbcCredentialsProvider {
/**
* @return JdbcCredentials which caller can use for authentication purpose
*/
JdbcCredentials getJdbcCredentials();
/**
* Instructs the provider to refresh or renew credentials.
* Default behavior is no-op.
*/
default void refresh() {
// no need to refresh anything by default
}
}
```
```
public interface …
```

Add support for Custom Credentials Provider Class in JDBC connectors

---

pom.xml

Release is blocked for 10.8.x branch due to incorrect version in pom.xml which came after branch cut. 
- Fix release version for 10.8.x branch. Set it to 10.8.0-SNAPSHOT.

Fix release version for 10.8.x branch

---

src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialect.java
src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java
src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java
src/test/java/io/confluent/connect/jdbc/sink/JdbcDbWriterTest.java
src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java

When used with Kafka connect, there are cases where null values ​in the record ​are changed to default values.
In kafka-connect library v3.5, [`replace.null.with.default` option was added ](https://issues.apache.org/jira/browse/KAFKA-8713)to prevent null values ​​from always being replaced with default values ​​when converting json.
But, the column constraints related to default values ​​still remain in the record, so null values ​​are entered as default values ​​when building insert/update queries in JdbcSink.
I don't think there is a problem with the current query build logic where null values ​​are replaced with default values ​​if there is a default value constraint. However, since this connector used with kafka-connect, and kafka-connect supports replace.null.with.default. So I think …

ADD: add replace.null.with.default for JdbcSink

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java

Fixes https://github.com/confluentinc/kafka-connect-jdbc/issues/1445
Using `Time.SYSTEM;` instead of the newly introduced `new SystemTime();` so it is backwards compatible.
This change is present in **atleast** apache kafka versions >= `2.0.0`  and CP versions >= `6.0.0` and was introduced in https://github.com/apache/kafka/pull/2095
Tested locally with `'apache/kafka:3.9.0'`.

use Time.SYSTEM in JbdcSourceTask.java

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java

Utils.mkSet is removed from apache kafka. Utilities functions are meant for the repository and should not be used by clients. 
Removed the usage of kafka utility function Utils.mkSet

Removed usage of kafka utils mkSet

---

src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java

Utils.mkSet is removed from apache kafka. Utilities functions are meant for the repository and should not be used by clients.
Removed the usage of kafka utility function Utils.mkSet

CC-31262: Removed usage of kafka utils mkSet

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/test/java/io/confluent/connect/jdbc/util/DateTimeUtilsTest.java

[CC-31133](https://confluentinc.atlassian.net/browse/CC-31133)
Currently, nanosecond-precision timestamps are capped at the year 2262 due to the limitations of the Long data type's range which is a constraint to support maximum dates up to 9999-12-31.
As a solution, we configure the timestamp conversion as a BigInt to accommodate extended date ranges. This approach is currently applied to the nanos_string configuration, which simply converts the nanos_long value to a string. However, for dates beyond the year 2262, their nanosecond representation exceeds the maximum value of a Java Long. Therefore, we are updating nanos_string to correctly represent these extended values.
Test cases have been included in this doc - https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/4243293217/Microp …

Support Large Dates with Nanos Precision

---

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java
src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java
src/main/java/io/confluent/connect/jdbc/util/DateTimeUtils.java
src/test/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteriaTest.java

CC-31131 : Microsecond Precision timestamp support for JDBC Connectors.
Currently Microsecond Precision is not supported in the JDBC Connectors without the nanos_long config in timestamp granularity. 
REF - https://confluentinc.atlassian.net/wiki/spaces/~63a167967cde7bff9d76a990/pages/4128737414/Micro+Nanoprecision+Time+support+in+JDBC+Connectors
This PR introduces a new mode i.e. MICROS_LONG in the timestamp.granularity config which when configured only the microsecond precision timestamp will be produced in kafka records.
Test cases have been included in this doc - https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/4243293217/Microprecision+Large+Dates+support+in+JDBC+Connectors

Microsecond Precision timestamp support for JDBC Connectors

---

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java
src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java

An issue has occurred where the connector failed to resume processing the records after stopping for a rebalance activity. It has been identified that the table Monitor thread is unable to fetch the tables and hence, the tables_fetched config in task configs is set to false which has made the connector to stall. 
It is only after a resume operation has triggered the connector to restart and then the task thread to fetch the tables and start processing the records. Expecting a race condition which made the tables_fetched config not to get updated, adding few trace logs would help to debug the issue.
Enhanced the Trace logging which could be help to debug the issue on why the tables fetch is not being set to true. It could be whether the tables hasn't been fetched from the database, or …

Enhance Trace logging to check race condition in Table Fetch and Task configurations

---

src/main/java/io/confluent/connect/jdbc/validation/JdbcSourceConnectorValidation.java

Currently subclasses of JdbcSourceConnectorValidation are not able to use their own config and validation result to initialize the parent class.
Adds another constructor for `JdbcSourceConnectorValidation` which allows to set the below two variables from subclasses.
```
protected final JdbcSourceConnectorConfig config;
protected final Config validationResult;
```

Add another constructor for validation class

---

src/main/java/io/confluent/connect/jdbc/validation/JdbcSourceConnectorValidation.java

The `addConfigError` was private. Hence subclasses didn't have ability to use it.
Making it protected.

Make `addConfigError` protected

---

src/test/java/io/confluent/connect/jdbc/integration/AbstractJdbcSourceConnectorIT.java
src/test/java/io/confluent/connect/jdbc/integration/BaseConnectorIT.java
src/test/java/io/confluent/connect/jdbc/integration/PostgresJdbcSourceConnectorIT.java

Plugins using kafka-connect-jdbc as external dependency should be able to run a sanity test using real container.
- Implemented an abstract IT which checks the behavior for all 4 modes. Individual plugins can just plug-in the testcontainers dependency and get a fully running IT.
- Exemplifies how to use this with implementing for postgres

CC-36952 -- Add all modes IT using testcontainers

---

src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java
src/test/resources/log4j.properties

testTableLocksWithStreamingReads was flaky and lead to productivity dip
Before the recent record queue enhancements, `poll` function was responsible to make the DB calls. This test relied on the old behaviour, hence before polling it expected no locks to be taken. 
Howeverm after change in implementation now querying DB part is done by some other thread, hence it's not tied to poll.

Fix flakiness due to testTableLocksWithStreamingReads

---

src/test/java/io/confluent/connect/jdbc/integration/BaseConnectorIT.java
src/test/java/io/confluent/connect/jdbc/integration/PostgreSqlDialectIT.java
src/test/java/io/confluent/connect/jdbc/sink/integration/AbstractJdbcSinkConnectorIT.java
src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresJdbcSinkConnectorIT.java

At present, only derby based tests are present. Although they are verifying a lot of functionalities, it's always better to verify major functionalities by running real databases.
This introduces `AbstractJdbcSinkConnectorIT` which can be easily extended for testing a particular database. All it requires is testcontainers setup and some commands to be provided by overriding the abstract functions.
- Create AbstractJdbcSinkConnectorIT with comprehensive test coverage for:
* insert.mode config (insert, upsert, update)
* auto.create and auto.evolve configs
* timestamp.fields.list with microsecond precision
* pk.mode configurations (kafka, record_key)
* fields.whitelist functionality
* delete.enabled with tombstone records
- Add PostgresJdbcSinkConnectorIT implementation using Testcontainers …

CC-37035 -- Add JDBC Sink Connector integration tests
