confluentinc/kafka-connect-jdbc

pom.xml, src/main/java/io/confluent/copycat/jdbc/BulkTableQuerier.java, src/main/java/io/confluent/copycat/jdbc/DataConverter.java, src/main/java/io/confluent/copycat/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/copycat/jdbc/JdbcSourceConnectorConstants.java, src/main/java/io/confluent/copycat/jdbc/JdbcSourceTask.java, src/main/java/io/confluent/copycat/jdbc/TableQuerier.java, src/main/java/io/confluent/copycat/jdbc/TimestampIncreasingTableQuerier.java, src/main/java/io/confluent/copycat/jdbc/util/StringUtils.java, src/test/java/io/confluent/copycat/jdbc/JdbcSourceConnectorTest.java, src/test/java/io/confluent/copycat/jdbc/JdbcSourceTaskConversionTest.java, src/test/java/io/confluent/copycat/jdbc/JdbcSourceTaskLifecycleTest.java, src/test/java/io/confluent/copycat/jdbc/JdbcSourceTaskTestBase.java, src/test/java/io/confluent/copycat/jdbc/JdbcSourceTaskUpdateTest.java
@ewencp Can you review it when you have time? Thanks!
=> Refactor copycat-jdbc to work with kakfa and copycat data API

src/main/java/io/confluent/copycat/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/copycat/jdbc/JdbcSourceConnectorConfig.java, src/main/java/io/confluent/copycat/jdbc/TableMonitorThread.java, src/test/java/io/confluent/copycat/jdbc/TableMonitorThreadTest.java
=> Poll in background for changes the set of tables and trigger reconfiguration when tables are added or removed.

docs/index.rst
=> Minor doc fix

checkstyle/checkstyle.xml, pom.xml, src/main/java/io/confluent/connect/jdbc/DataConverter.java, src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/connect/jdbc/JdbcSourceConnectorConfig.java, src/main/java/io/confluent/connect/jdbc/JdbcSourceTask.java, src/main/java/io/confluent/connect/jdbc/JdbcSourceTaskConfig.java, src/main/java/io/confluent/connect/jdbc/JdbcUtils.java, src/main/java/io/confluent/connect/jdbc/TableMonitorThread.java, src/main/java/io/confluent/connect/jdbc/TimestampIncrementingTableQuerier.java, src/main/java/io/confluent/connect/jdbc/util/StringUtils.java
The style is similar to Kafka, with small differences:
* No import controls
* indentation of 2
* No "unnecessary parenthesis" check - we use unnecessary parenthesis on occasion (mostly for trenary ops) and I think its good
* Different headers (duh)
=> adding checkstyle checks and the traditional minor fixes related

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java
=> Task config should not show up in connector config

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnectorConfig.java
=> Add table.blacklist display name

src/main/java/io/confluent/connect/jdbc/JdbcUtils.java
=> Close all ResultSets in JdbcUtils.

src/main/java/io/confluent/connect/jdbc/DataConverter.java
=> Fix thread-safety of date/time conversions in DataConverter

README.md, config/sink-quickstart-sqlite.properties, config/source-quickstart-sqlite.properties, docs/index.rst, docs/sink_config_options.rst, docs/sink_connector.rst, docs/source_config_options.rst, docs/source_connector.rst, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
Restructue the docs to separate pages for the source and the sink
Also adding some 0.10.0 fields to the ConfigDef
=> CC-231: Add JDBC Sink Connector documentation

docs/changelog.rst
=> 3.0.1 changelog

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
This is the suggested fix for Issue #118.
Kindly review.
=> sink: Type mismatch for connectionPassword

src/main/java/io/confluent/connect/jdbc/sink/dialect/DbDialect.java, src/main/java/io/confluent/connect/jdbc/sink/dialect/HANADialect.java, src/test/java/io/confluent/connect/jdbc/sink/dialect/HANADialectTest.java
Support HANA Dialect for the JDBC Sink Connector
=> Sink: Support for HANA Dialect

docs/sink_config_options.rst, docs/source_config_options.rst, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
Needed a local Kafka build with https://github.com/apache/kafka/pull/1964 to generate the docs using `ConfigDef.toEnrichedRst()`
=> CC-331: Config option doc updates

pom.xml, src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java, src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java, src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java, src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java, src/test/java/io/confluent/connect/jdbc/JdbcSourceConnectorTest.java, src/test/java/io/confluent/connect/jdbc/sink/JdbcDbWriterTest.java, src/test/java/io/confluent/connect/jdbc/sink/SqliteHelper.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java, src/test/java/io/confluent/connect/jdbc/source/TableMonitorThreadTest.java
=> CC-263: Prevent retrying queries with a broken connection

src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java
=> Connection.isValid() expects seconds not milliseconds

src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java
=> CC-432: Missing PreparedStatement.close()

src/main/java/io/confluent/connect/jdbc/sink/dialect/SqlServerDialect.java, src/test/java/io/confluent/connect/jdbc/sink/dialect/SqlServerDialectTest.java
=> SqlServerDialect's upsert query placeholders should be in the order keyCols*, cols*

docs/changelog.rst
=> 3.3.0-changelog

src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java
Added DB2 UDB for AS/400 handling to  getCurrentTimeOnDB method. Basically the same as Apache Derby.
=> Fixed issue #211 - get current timestamp on DB2 UDB for AS/400

docs/sink_config_options.rst, docs/source_config_options.rst, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
Regenerated the documentation.
=> MINOR: Formatting corrections to the connector config documentation

docs/source_connector.rst
https://confluentinc.atlassian.net/browse/DOCS-452
=> DOCS-452 - Add note about location of test.db file

docs/source_config_options.rst
https://confluentinc.atlassian.net/browse/DOCS-460
=> DOCS-460 - fix bullet formatting error

src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java, src/test/java/io/confluent/connect/jdbc/source/TableMonitorThreadTest.java
Fix for https://confluentinc.atlassian.net/browse/CC-2250
=> Fail if the filtered tables list has duplicates based on unqualified table name

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java, src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java, src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingOffset.java
Upgraded a couple of trace logs to debug.
Added a bunch of new logs to give us more insight into how JDBC runs.
https://confluentinc.atlassian.net/browse/CC-2900
=> CC-2900: Update logs in JDBC Sink and Source

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
fixes https://github.com/confluentinc/kafka-connect-jdbc/issues/388
=> Fix update where with multiple keyColumns

checkstyle/suppressions.xml, src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java
=> Update the SQL Server dialect to properly retrieve auto incremented column information.

src/test/java/io/confluent/connect/jdbc/source/MockTime.java
=> MINOR: Update MockTime to use updated AK Time interface

src/main/java/io/confluent/connect/jdbc/dialect/SqliteDatabaseDialect.java, src/test/java/io/confluent/connect/jdbc/dialect/SqliteDatabaseDialectTest.java
Backporting 
PR https://github.com/confluentinc/kafka-connect-jdbc/pull/596#event-2201158920 to 5.0.x
=> CC-3812: Sqlite timestamp parse error

src/main/java/io/confluent/connect/jdbc/source/BulkTableQuerier.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java
Signed-off-by: Arjun Satish <arjun@confluent.io>
=> CC-6773: Abort source task if all columns were not converted correctly.

checkstyle/suppressions.xml, src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java, src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java
Try to fix bug described in #171 
@gharris1727 pls have a look.
=> * Handling deletes with schema !null

pom.xml, src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/dialect/MySqlDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java, src/test/java/io/confluent/connect/jdbc/source/integration/BaseOOMIntegrationTest.java, src/test/java/io/confluent/connect/jdbc/source/integration/MySQLOOMIT.java, src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java
Also refactors OOM integration test, add an OOM IT for MySQL
=> Move setFetchSize to GenericDatabaseDialect

src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java
=> MINOR: Only apply fetchsize to source dialect

Jenkinsfile, pom.xml, src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialectProvider.java, src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/sink/DbStructure.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingCriteria.java, src/main/java/io/confluent/connect/jdbc/util/ExpressionBuilder.java, src/main/java/io/confluent/connect/jdbc/util/StringUtils.java
We need the release maven plugin for independent releases. Also, some adjustment in version variables
Add the plugin and apply fixes
master only. 10.0.x will be created after this commit.
=> CC-11861: Add release maven plugin and prepare 10.0 release

src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java, src/test/java/io/confluent/connect/jdbc/sink/JdbcSinkTaskTest.java, src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java, src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresViewIT.java
This reverts commit a88be829c3018c8af6c0fd44d04fb28608920c85.
=> Revert "CC-9435: Implement DLQ Support in JDBC Sink (#890)"

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java
There is a conflict when pint merge
manually merge it
=> Manually merge 5.5.x to master

src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfigTest.java
=> Manually pint merge 5.5.x to 10.0.x

pom.xml
https://snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-571481
Apply https://github.com/confluentinc/kafka-connect-jdbc/commit/50211b1dfaf293e05fee4eebb5be02084586dd4a to 5.4.x as well.
=> Upgrade org.postgresql:postgresql to version 42.2.19

pom.xml, src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java, src/test/java/io/confluent/connect/jdbc/dialect/BaseDialectTest.java, src/test/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialectTest.java, src/test/java/io/confluent/connect/jdbc/sink/integration/PostgresDatatypeIT.java
Postgres wants arrays.
Give Postgres arrays.
=> FF-2998: Postgres primitive array support.

src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java
=> Fix checkstyle by updating Apache license header to Community License

pom.xml
This is to resolve https://github.com/advisories/GHSA-v7wg-cpwc-24m4
Upgraded org.postgresql:postgresql. This will be pint merged to master branch.
=> Upgrade  org.postgresql:postgresql

.github/CODEOWNERS, pom.xml
The existing owners was under permissive
Add a better handle for broader check and reviews
=> Update CODEOWNERS to Confluent Connect team

src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java, src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java, src/test/java/io/confluent/connect/jdbc/source/EmbeddedDerby.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
Failing pint merge due to conflicts
```
14:48:09    from 10.2.x to 10.3.x
14:48:09      7aa68f84  Merge branch '10.1.x' into 10.2.x
14:48:09      ae390d9c  Merge branch '10.0.x' into 10.1.x
14:48:09      2241acb9 CCDB-5069: Fix data loss in timestamp mode due to in-mem offsets (#1239)
14:48:09    from 10.3.x to 10.4.x
14:48:09    from 10.4.x to 10.5.x
14:48:09    from 10.5.x to master
14:48:12  Do you want to merge the commits to all downstream branches? [y/N]: Merging 10.2.x into 10.3.x
14:48:12  2022-09-29 09:18:11,865 workspace.commands.merge INFO skip_commits:{'chore: Set project version and resolve dependencies', 'chore: Resolved updated dependencies', '[ci skip]', 'chore: Set project to dev version'}
14:48:12  2022-09-29 09:18:11,865 workspace.commands.merge INFO Verifying …
```
=> Merge Conflict Resolution (from 10.2.x to 10.3.x)

src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java, src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java, src/test/java/io/confluent/connect/jdbc/source/EmbeddedDerby.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
Failing pint merge due to conflicts
```
14:48:09    from 10.3.x to 10.4.x
14:48:09      7aa68f84  Merge branch '10.1.x' into 10.2.x
14:48:09      ae390d9c  Merge branch '10.0.x' into 10.1.x
14:48:09      2241acb9 CCDB-5069: Fix data loss in timestamp mode due to in-mem offsets (#1239)
14:48:09    from 10.4.x to 10.5.x
14:48:09    from 10.5.x to master
14:48:12  Do you want to merge the commits to all downstream branches? [y/N]: Merging 10.2.x into 10.3.x
14:48:12  2022-09-29 09:18:11,865 workspace.commands.merge INFO skip_commits:{'chore: Set project version and resolve dependencies', 'chore: Resolved updated dependencies', '[ci skip]', 'chore: Set project to dev version'}
14:48:12  2022-09-29 09:18:11,865 workspace.commands.merge INFO Verifying commit:`2241acb9 CCDB-5069: Fix data loss …
```
=> CCDB-5069: Fix data loss in timestamp mode due to in-mem offsets (#1239)

pom.xml
=> Fixing https://confluentinc.atlassian.net/browse/CC-17951

pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 10.3.x to 10.4.x)

pom.xml
=> Resolve merge conflict for pint merge

licenses.html, pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 5.5.x to 10.0.x)

pom.xml
=> Resolving merge conflict from 10.3.x to 10.4.x

pom.xml, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
FOSSA is incorrectly assuming the Oracle JDBC related version as 21.9.0.0. Explicitely setting version to 19.7.0.0.
=> CC-19887 & CC-19797: FOSSA license fix & holdlock message/group update.

pom.xml, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java
manually fixing pint merge w.r.t https://github.com/confluentinc/kafka-connect-jdbc/pull/1324.
=> Cc 19797 fix pint merge conflict

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialects.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java, src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java, src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskLifecycleTest.java, src/test/java/io/confluent/connect/jdbc/source/JdbcSourceTaskUpdateTest.java
=> CC-19550 CC-19551 Standard logs jdbc

pom.xml
[CC-19887](https://confluentinc.atlassian.net/browse/CC-19887)
[CC-19887]: https://confluentinc.atlassian.net/browse/CC-19887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CC-19887] flattened oracle related dependencies to remove pom file

pom.xml, src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java, src/test/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialectTest.java, src/test/java/io/confluent/connect/jdbc/sink/integration/OracleDatatypeIT.java
https://confluentinc.atlassian.net/browse/RCCA-12408
https://github.com/jOOQ/jOOQ/issues/7548
- [x ] no
- [x ] Integration tests
=> Fix underflow issue with Oracle JDBC

.semaphore/project.yml, .semaphore/semaphore.yml, Jenkinsfile, service.yml, sonar-project.properties, src/test/java/io/confluent/connect/jdbc/source/integration/PauseResumeIT.java
Cherry-pick the changes to the lowest valid .x branch and open a PR.
Then [pint merge](https://jenkins.confluent.io/job/tools-autotasks/job/tools-autotasks/job/apply-pint-merge/build?delay=0sec) the changes from that .x branch.
1) Disables the deploy in the Jenkinsfile.
2) Adds the service-bot config (service.yml) and semaphore files generated by service-bot
[Read the background and motivation](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3033867557/CI+System+Migration+Jenkins-+Semaphore#Background-and-Motivation)  
Please merge this PR ASAP because we plan on shutting down Jenkins by the end of the year.
=> CC-24280 Migration: Jenkins -> Semaphore

Jenkinsfile, pom.xml, sonar-project.properties
- Bumped up connect-plugin-parent to use jacoco plugin and generate report.
- Added sonar-project.properties file.
=> CC-23123 : Integrated Sonarqube code quality check

Jenkinsfile, pom.xml, sonar-project.properties
Conflict resolution for merging 5.1.x to 5.2.x
=> Conflict resolution for merging 5.1.x to 5.2.x

Jenkinsfile, pom.xml, sonar-project.properties
=> Resolved conflicts from 5.5.x to 10.0.x

Jenkinsfile, pom.xml, sonar-project.properties
=> Resolved conflicts from 10.2.x to 10.3.x

Jenkinsfile, pom.xml
=> Resolved conflicts from 10.5.x to 10.6.x

pom.xml
For merge conflict resolution
https://github.com/confluentinc/kafka-connect-jdbc/pull/1423
=> change snapshot version

pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 10.7.x to master)

pom.xml
=> Fix release process

.semaphore/semaphore.yml, pom.xml
Doing the same as elasticsearchsink does.
---
[Job](https://semaphore.ci.confluent.io/jobs/f82d2bce-75a3-4825-9447-69ac1909c901) failed which rauns `mvn -Dcloud -Pjenkins -U -Dmaven.wagon.http.retryHandler.count=10 --batch-mode --no-transfer-progress clean verify install dependency:analyze validate`
from the `semaphore.yml`.
Stack trace:
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:7.4.4:check (default) on project kafka-connect-jdbc: Fatal exception(s) analyzing kafka-connect-jdbc: One or more exceptions occurred during analysis:
[ERROR] 	UpdateException: Unable to download meta file: https://s3-us-west-2.amazonaws.com/confluent-packaging-tools/nvd.nist.gov/nvdcve-1.1-modified.meta
[ERROR] 		caused by DownloadFailedException: Download failed, unable to retrieve …
```
=> Skip dependency check

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcDbWriter.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkTask.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java, src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java, src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java, src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java, src/main/java/io/confluent/connect/jdbc/source/TimestampTableQuerier.java, src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java, src/main/java/io/confluent/connect/jdbc/util/JdbcDriverInfo.java
=> CC-18911 - Added INFO logs for better debugging

src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java, src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java, src/main/java/io/confluent/connect/jdbc/util/JdbcDriverInfo.java
This PR enhances the logging in order to debug a potential race condition while updating the task configs. 
[CC-30123](https://confluentinc.atlassian.net/browse/CC-30123) - Update the misleading log line for the JDBC Driver Version.
[CC-30123]: https://confluentinc.atlassian.net/browse/CC-30123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enhanced INFO Logging to check for Race Condition

.semaphore/project.yml, .semaphore/semaphore.yml, pom.xml, service.yml
The latest versions have the fix but the older versions were missing this.
=> CC-30786 CC-30787 : Update sqlite and postgresql

src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/dialect/OracleDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/dialect/SybaseDatabaseDialect.java, src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java, src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java, src/main/java/io/confluent/connect/jdbc/sink/PreparedStatementBinder.java, src/test/java/io/confluent/connect/jdbc/sink/JdbcDbWriterTest.java, src/test/java/io/confluent/connect/jdbc/sink/PreparedStatementBinderTest.java
(cherry picked from commit faa9e54c220fdb240e10efadb70ff0efb4f02fee)
=> ADD: add replace.null.with.default for JdbcSink (#1433)

pom.xml
https://semaphore.ci.confluent.io/jobs/097b8151-7487-4224-930e-0563e8bd150e
Bring in changes from 10.7.x+ to solve this
=> skip dependency checks for 10.6.x

src/main/java/io/confluent/connect/jdbc/source/TableQuerierProcessor.java
**Query Processing Logic:**
* The loop in `process` now checks both `destination.isRunning()` and that `tableQueue` is not empty, preventing unnecessary processing when there are no tables left to query.
**Error Handling and Logging:**
* The SQL exception log message in `handleSqlException` has been clarified to focus on the table and retry attempt, and the exception object is now logged at the end for better readability.
* The retry logic in `handleSqlException` now calls `resetAndRequeueHead` with `false` instead of `true`, changing how the processor handles failed queries before retrying
=> fix NPE, reset the querer and fix error log

VERSION_SELECTION.md
Documenting the new strategy of version selection for the next artifact being released in code artifactory.
Documenting the new strategy of version selection for the next artifact being released in code artifactory.
=> CC-36978 -- Add updated versioning documentation

src/test/java/io/confluent/connect/jdbc/integration/PostgreSqlDialectIT.java
As of today, there is no test which ensures that dialect is working correctly.
mplements a dialect IT similar to snowflake's dialect IT.
Snowflake source's dialect IT -- https://github.com/confluentinc/kafka-connect-snowflake-source/blob/master/src/test/java/io/confluent/connect/snowflake/jdbc/integration/SnowflakeDialectIT.java
=> CC-37002 - Add postgres dialect IT (#1569)
